### ISSUE TITLE
GMX = Instant Client Crash

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#10]
I'm pretty sure this would be caused by RemoveBuildingForPlayer being repeated when OnPlayerConnect is called on the same player that was already connected. The 'building' (vending machines in our case) can't be removed twice.

**Comment by Crayder** [comment]
Fixed by moving this line:
	RemoveDefaultVendingMachines(playerid);
From ScriptInit to OnFilterScriptInit and running a loop through all players to define playerid.

**Comment by oscar-broman** [comment]
If you move it there, it would never get called if the include is used in a gamemode.

So when GMX is being done, it needs to remember which players already had the buildings removed?

**Comment by Crayder** [comment]
Yeah, but but how would you be able to do that?

**Comment by oscar-broman** [comment]
Perhaps @Y-Less has an idea how to persist data in-memory during `rcon gmx`?

**Comment by Crayder** [comment]
Hmm... Maybe you could write a file in OnGameModeExit containing the time exited and a list of players connected at the time... Then OnGameModeInit, read the file and if the time was less than say 5 minutes collect the players names... Delete the file whether or not it was less than 5 minutes... Compare the names for each player connecting within the next 5 minutes... If they were online at the time gmx'd (name matched on of which in the array), don't remove the objects... This is not a very secure procedure but I don't know of any other way to hold memory of a server restart...

**Comment by Crayder** [comment]
I wonder if @Y-Less has seen this yet...

**Comment by Y-Less** [comment]
I had not; I'm not sure why I got a notification for the second tag of my name but not the first...

Anyway, it is tricky without explicitly knowing that there is a filterscript running along side the mode.  I looked at a few options - I was actually unclear about whether PVars are deleted at GMX and not just in a true OnPlayerDisconnect.  Otherwise, files may be the only option.  I also debated sqlite `:memory:` databases but they will be closed with the mode I THINK - I don't know what happens if they aren't explicitly closed in PAWN code but just left to the server to clean up.

**Comment by Crayder** [comment]
It would be so much easier if this thing was fixed in a SA:MP release all together, or just a way to check that the 'building' exists in the first place.

**Comment by oscar-broman** [comment]
What about `setproperty` and `getproperty`?

**Comment by Y-Less** [comment]
No, I know those are cleared on GMX.

**Comment by oscar-broman** [comment]
It doesn't crash on GMX (or filter-script reload) for me. Are you sure it's nothing else causing it?

**Comment by oscar-broman** [comment]
@Y-Less I think we were over-thinking this. `IsPlayerConnected` returns true in `OnGameModeInit` - that's all the necessary information!

**Comment by Y-Less** [comment]
I was thinking more about a generic fix for any objects (though there are WAY more issues with that...)  But you're right, we clearly were overthinking it for a known set of removals.
