### ISSUE TITLE
weapon-config crash

### ISSUE THREAD

**Issue by sampwide** [oscar-broman/samp-weapon-config#100]
Crash log: https://pastebin.com/22syMRtq
Includes I'm using: https://pastebin.com/8fQKa9kz
My OnPlayerDamage CB: https://pastebin.com/iE1hg5NT

More info: So I'm using this include for a very long time and i didn't have problems with it until now.
Everything works normal when there are no players streamed in. So I can normally fall and take damage or even update my HP/armour. But, when there is player streamed in and I take damage (like fall or hit by another player) the server just crashes. Even if I update my hp through include function it still crashes. I have tried so many solutions and none of them didn't work well. 

If you need more info, please tell me.

P.S. I'm using newest versions of weapon-config and SKY.

Regards.

**Comment by ADRFranklin** [comment]
I am aware of the issue, please use a older version for now. 
I am finding time to fix the issue.

**Comment by sampwide** [comment]
Can you give me link or something, I'm new to this..

**Comment by ADRFranklin** [comment]
The problem is SKY, so please use the SKY repo. 
SKY: https://github.com/oscar-broman/SKY

**Comment by sampwide** [comment]
Thank you, I didn't know that this version isn't finished.
