### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by codakkk** [oscar-broman/samp-weapon-config#101]
I'm having a strange behaviour where each shot by a specific player gets invalidated.
It's a RolePlay gamemode and there's a so called "death system", where a player need to accept his death before getting respawned.
But, If a player gets out death system (by getting healed), each shot by himself is invalidated.

Logs:
`(wc:1) OnPlayerWeaponShot(1 shot 0 with 24 at -0.063476, 0.112670, 0.441425)
(wc:1) (shot) last: 9552 last 3: 17144
(wc:1) OnPlayerGiveDamage(1 gave 46.200000 to 0 using 24 on bodypart 3)
(wc:1) (hit) last: 9521 last 3: 17147
(wc:1) WARN: last shot not valid`

**Comment by ADRFranklin** [comment]
I'm going to need a lot more information about how you are using SKY, to determine any possible solutions for you to take.

**Comment by ADRFranklin** [comment]
That would be helpful, try to provide as much information as you can. But do remove any sensitive information like keys, passwords, tokens etc.

**Comment by codakkk** [comment]
OnPlayerDeath:
`public OnPlayerDeath(playerid, killerid, reason)
{
	if(IsPlayerNPC(playerid))
		return 1;
	
	if(killerid != INVALID_PLAYER_ID)
		Log(Character_GetOOCName(playerid), Character_GetOOCName(killerid), "OnPlayerDeath", reason);
	
	
	SetPlayerDrunkLevel(playerid, 0);

	if(Character_IsAlive(playerid))
	{
		new vid = GetPlayerVehicleID(playerid);
		if(reason == 51 && vid > 0) //(IsAHelicopter(vid) || IsAPlane(vid)))
		{
			Character_SetDeathState(playerid, DEATH_STATE_NONE);
		}
		else
		{
			Character_SetInvincibleForTime(playerid, 2);
			Character_SetDeathState(playerid, DEATH_STATE_INJURED);
		}
	}
	else if(Character_IsInjured(playerid))
	{
		Character_SetDeathState(playerid, DEATH_STATE_NONE);
	}
	
	new newDeathState = Character_GetDeathState(playerid);

	// Just a workaround for unable to hook OnPlayerDeath with weaponconfig
	CallLocalFunction(#OnCharacterDeath, "ddd", playerid, killerid, reason);

	GetPlayerPos(playerid, PlayerDeathState[playerid][pDeathX], PlayerDeathState[playerid][pDeathY], PlayerDeathState[playerid][pDeathZ]);
	GetPlayerFacingAngle(playerid, PlayerDeathState[playerid][pDeathA]);

	PlayerDeathState[playerid][pDeathInt] = GetPlayerInterior(playerid);
	PlayerDeathState[playerid][pDeathWorld] = Character_GetVirtualWorld(playerid);
	PlayerDeathState[playerid][pDeathVehicle] = GetPlayerVehicleID(playerid);

	if(newDeathState == DEATH_STATE_INJURED)
	{
		if(killerid != INVALID_PLAYER_ID)
			SendFormattedMessage(playerid, COLOR_ERROR, "(( Sei stato ferito da \"%s\". ))", Character_GetRolePlayName(killerid));
		SendFormattedMessage(playerid, COLOR_GREEN, "Digita /danni %d per lo storico danni.", playerid);
		Character_SetDeathTime(playerid, GetTickCount());
	}
	else
	{
		Character_ResetWeapons(playerid);
	}
	Internal_UpdateDeathState(playerid);

	return 1;
}`

**Comment by codakkk** [comment]
And Internal_UpdateDeathState:
`static Internal_UpdateDeathState(playerid)
{
	new deathState = Character_GetDeathState(playerid);
	if(deathState > 0)
	{
		PlayerTextDrawShow(playerid, pDeathTextDraw[playerid]);
		if(deathState == DEATH_STATE_INJURED)
		{
			if(IsValidDynamic3DTextLabel(PlayerDeathState[playerid][pDeathText]))
				DestroyDynamic3DTextLabelEx(PlayerDeathState[playerid][pDeathText]);
			
			new str[64];
			
			if(Character_IsMasked(playerid))
				format(str, sizeof(str), "(( QUESTO GIOCATORE È FERITO. /danni #%07d ))", Character_GetID(playerid));
			else
				format(str, sizeof(str), "(( QUESTO GIOCATORE È FERITO. /danni %d ))", playerid);
			
			PlayerDeathState[playerid][pDeathText] = CreateDynamic3DTextLabel(str, COLOR_ADMIN, 0.0, 0.0, 0.5, 30.0, playerid, INVALID_VEHICLE_ID, 1, -1, -1, -1, 100.0);
			
			Character_SetHealth(playerid, 20.0);
			Character_SetArmour(playerid, 0.0);

			SetCameraBehindPlayer(playerid);

			new Float:x, Float:y, Float:z, Float:a, interior, world;
			
			Character_GetDeathStateData(playerid, x, y, z, a, interior, world);

			SetPlayerPos(playerid, x, y, z);
			SetPlayerFacingAngle(playerid, a);
			SetPlayerInterior(playerid, interior);
			Character_SetVirtualWorld(playerid, world);

			Character_AMe(playerid, "è in gravi condizioni.");

			SendFormattedMessage(playerid, COLOR_ERROR, "Sei in gravi condizioni, tra %d secondi puoi accettare la morte utilizzando \"/accetta morte\".", INJURED_TIME_AS_SECONDS);
			CallLocalFunction(#OnCharacterInjured, "d", playerid);
		}
		Internal_ApplyDeathAnim(playerid);
	}
	return Y_HOOKS_CONTINUE_RETURN_1;
}`

**Comment by codakkk** [comment]
And this is the code that resets death state:
`
	if(IsValidDynamic3DTextLabel(PlayerDeathState[playerid][pDeathText]))
		DestroyDynamic3DTextLabelEx(PlayerDeathState[playerid][pDeathText]);
	PlayerTextDrawHide(playerid, pDeathTextDraw[playerid]);
	new CleanPlayerDeathState[e_DeathState];
	PlayerDeathState[playerid] = CleanPlayerDeathState;
	DeathState{playerid} = DEATH_STATE_NONE;
`

**Comment by ADRFranklin** [comment]
Can you confirm you are using the latest version of weapon-config?

**Comment by codakkk** [comment]
What do you mean by MRE?

**Comment by ADRFranklin** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by codakkk** [comment]
Sure. I'll try to reproduce it on a blank gamemode.

**Comment by ADRFranklin** [comment]
if you are unable to reproduce it, that would mean that weapon-config is not to blame for the issue, in most cases. However if you somehow later able to reproduce it, then feel free to reply here again and I will do what I can do solve it.

You might want to try different things, to maybe spark the issue again.
