### ISSUE TITLE
Adding IsPlayerDead function

### ISSUE THREAD

**Issue by NexiusTailer** [oscar-broman/samp-weapon-config#103]
I know we already have IsPlayerSpawned if we want to check whether some player spawned or not (and it is also include death cases, returning 0 if the player dead ie he's not spawned), but if I want to exactly check whether the player is dead I can't do it right now as this player can be just in spectating or whatever. Checking weapon-config's death can't be done through GetPlayerState as well, because PLAYER_STATE_WASTED will be only the actual death.

**Comment by NexiusTailer** [comment]
IsPlayerDying found, sorry for stupidity

**Comment by Zorono** [comment]
is `weapon-config` a requirement to use `IsPlayerDying` or you're including it from somewhere else ??
