### ISSUE TITLE
Several vulnerabilities with some weapons

### ISSUE THREAD

**Issue by NexiusTailer** [oscar-broman/samp-weapon-config#104]
There is an ability to send invalid damage which will be processed without proper verification of its validity. More precisely, a cheater can send OnPlayerTakeDamage with reasons such as 53 (WEAPON_DROWN) and 54 (WEAPON_COLLISION) indicating the issuerid (thereby fake dying from other players so they'll be considered and maybe punished by gm logic as killers), although these damage reasons don't imply issuerid presence.

Also these is an ability to send damage reason 49 (WEAPON_VEHICLE) and 50 (WEAPON_CARPARK or WEAPON_HELIBLADES) with issuerid even when he is not in any vehicle.

**Comment by ADRFranklin** [comment]
Thanks for the report, I will look into this. Do you have a way to test this or know of a hack tool that could assist in testing it?

**Comment by Crayder** [comment]
s0biet (few versions) has this, and probably some sampfuncs script for 0.3.7

**Comment by ADRFranklin** [comment]
Thanks, will try them out.

**Comment by NexiusTailer** [comment]
I have some .lua scripts but I think it's a bad idea to share such cheats just here, so I can advise (in addition to Crayder's links) to emulate this from the server side - just call from your gm OnPlayerTakeDamage with all nessecary params.

**Comment by ADRFranklin** [comment]
[weapon-config.zip](https://github.com/oscar-broman/samp-weapon-config/files/4147873/weapon-config.zip)

Could you try that and tell me if this fixes the two issues?

**Comment by NexiusTailer** [comment]
Thank you for this checks, but I've noticed 2 issues:
1.
```
		if(weaponid == WEAPON_COLLISION
		|| weaponid == WEAPON_DROWN
		|| weaponid) { // <- Here
			return 0;
		}
```
The last check were probably added by mistake as the weapon isn't mentioned (so that it'll be checked as 'everything that's not 0')

2 . I'm not sure now about WEAPON_VEHICLE to check it if the issuerid should be in vehicle and should be valid at all, because there are a few cases when you can get under the wheels of unoccupied vehicle and having some damage from this... Albeit I don't know at this moment what exactly the damage reason for this and how will weapon-config behave in such case.

**Comment by ADRFranklin** [comment]
Whoops, haha yeah that first one was an accident.

Well that vehicle check only happens if the `issuerid` is not invalid anyway. So that check wouldn't apply to unoccupied vehicles.

**Comment by NexiusTailer** [comment]
Okay, then it sound good. Actually I've already made some similar checks when I found it (as it was important to quickly fix it on one big server), but I wasn't sure about the effectiveness of my implementation (I've made it inside ProcessDamage with many unnecessary conditions) and as a result you've done it better :)

**Comment by ADRFranklin** [comment]
Thanks :)
This has now been added to the repo. Feel free to re-open this issue, should you find any issues with the changes.
