### ISSUE TITLE
s_WeaponRange only considers bullet weapon distances

### ISSUE THREAD

**Issue by NexiusTailer** [oscar-broman/samp-weapon-config#108]
An array named s_WeaponRange is mainly intended for having an ability to make your custom weapon ranges which is reasonable for bullet weapons where OnPlayerWeaponShot is being called at any distances, but the second purpose of the array is also to check damage for invalid and other spoofing attempts from cheaters. So now there is an ability for them to spoof non-bullet weapons damage at a long distance (being in stream) as there is no any check for it.

The possible solution could be to fill s_WeaponRange array with max valid distances for each weapon (not only for bullet weapon), compare each weapon's dist in the damage event with max dist from the array and at the same time make additional check in SetWeaponMaxRange to be able to use it only for bullet type of guns.

**Comment by NexiusTailer** [comment]
Well there is actually a check [for melee](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L4468) [and high rate](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L4589) weapons but you can see it's just an average-calculated and rather a large value. I think it should be a distance for every weapon in array instead so any attempts of fake damaging will require a very close location to the victim.

**Comment by ADRFranklin** [comment]
This is something that could be done, if I find time I will start working on this issue. Unless someone who has time feels like they want to PR it.

**Comment by NexiusTailer** [comment]
Closed in advance to the mentioned PR that should solve this.
