### ISSUE TITLE
Streaming in when exiting (maybe entering) vehicles.

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#11]
When I exit a vehicle all the dynamic objects around me flash and objects in the distance that should be streamed in are not. This flash causes me to fall through the ground of my maps.

I'm guessing that this has something to do with OnPlayerStateChange because it happens when exiting and sometimes entering vehicles. More specifically I'm guessing it's SKY's functions in WC_SpawnForStreamedIn which is called in OPSC. 

EDIT: I was correct before, the cause is SpawnForStreamedIn (pretty sure after a few test attempts). When I comment the following section of OPSC, the bug does not occur.

	/*if (newstate == PLAYER_STATE_ONFOOT) {
		if (oldstate == PLAYER_STATE_DRIVER || oldstate == PLAYER_STATE_PASSENGER) {
			new Float:vx, Float:vy, Float:vz;
			GetPlayerVelocity(playerid, vx, vy, vz);

			if (vx*vx + vy*vy + vz*vz <= 0.05) {
				WC_SpawnForStreamedIn(playerid);
			}
		}
	}*/

That narrows down to SpawnPlayerForWorld(playerid) because the only other two functions called in that function require players to be online, and I was alone. So this is a SKY bug. I haven't been able to test the other spots SpawnForStreamedIn is called because nobody has been online for me to test the knife stuff on.

__EDIT: I made a command to only run SpawnPlayerForWorld, most of the time this bug occurs. Sometimes the bug does not occur. So this is actually a SKY bug.__

**Comment by oscar-broman** [comment]
Do you use a streamer plugin? I suspect it has hooked SA-MP's `SpawnForWorld`.

For now, I think it's best to change that to `ClearAnimationsForPlayer` for all streamed-in players.
