### ISSUE TITLE
Death problem

### ISSUE THREAD

**Issue by valenda-s** [oscar-broman/samp-weapon-config#114]
Several of my players have reported issues relating to deaths. 

Here is a video: https://youtu.be/Pz0GpWOx2E4
I recommend watching in 1080p60, and at speed 0.25.

In this video, ID 19 is killed (which you can confirm by the death message in chat, and on the killboard), and then slides around on the floor for a few seconds before finally "dieing".

I am using the very latest weapon-config (8280236 4 days ago).

Any thoughts would be appreciated.

**Comment by ADRFranklin** [comment]
This would be related to SKY not weapon-config as such. Since this appears to be a syncing problem. Can I ask what version of SKY do you use?

**Comment by valenda-s** [comment]
Many thanks for the prompt response. Below is the requested information:

19/12/2019 12:32:05    ## SKY - 2.1.1 ##
19/12/2019 12:32:05
19/12/2019 12:32:05    (c) 2008 - Present | YSF Maintainers
19/12/2019 12:32:05    (c) 2015 | Oscar "Slice" Broman
19/12/2019 12:32:05
19/12/2019 12:32:05    Server Version: 0.3.7 R2
19/12/2019 12:32:05    Operating System: Linux
19/12/2019 12:32:05    Built on: Dec 12 2019 at 12:21:08

**Comment by ADRFranklin** [comment]
I will take a look some point tomorrow, and see if I can find the issue.

**Comment by ADRFranklin** [comment]
I am currently working on a fix for this, I believe I have found the issue and am currently awaiting for it to be tested and validated for production use.

**Comment by ADRFranklin** [comment]
@valenda-s This problem has been fixed in the latest version of SKY: https://github.com/oscar-broman/SKY/releases/tag/2.2.0

**Comment by Y-Less** [comment]
> 
> 
> I am currently working on a fix for this, I believe I have found the issue and am currently awaiting for it to be tested and validated for production use.


> I have found the issue


> I


...

**Comment by ADRFranklin** [comment]
This was posted before your fix, check the dates :D
also I mentioned you here as the solution to the fix :P
https://github.com/oscar-broman/SKY/issues/31#issuecomment-569377652
