### ISSUE TITLE
Valid hits rejected on drive-by

### ISSUE THREAD

**Issue by lassir** [oscar-broman/samp-weapon-config#12]
When the driver of a vehicle shoots another player on foot (i.e. drive-by), only the first few shots will be considered valid, and after that all shots fired by the driver are rejected. The reported reason why the hit was rejected is `One bullet hit n players`.

See https://gist.github.com/lassir/d8c255e9c64e8bc9bbb5#file-gistfile1-txt for server logs.

**Comment by oscar-broman** [comment]
It seems driver drive-by doesn't cause `OnPlayerWeaponShot` to get called. The check for this should be removed.

**Comment by oscar-broman** [comment]
It should work properly now.

To clarify the last commit, it doesn't remove all sanity checking from driver DB - only the checks that come from `OnPlayerWeaponShot` (because it's not called for driver DB).
