### ISSUE TITLE
Server Side Vehicle Health

### ISSUE THREAD

**Issue by InterSstellar** [oscar-broman/samp-weapon-config#121]
Please Release a version With Server Side Vehicle Health If You Can Please 💃 💃 💃

**Comment by ADRFranklin** [comment]
Though it is not the point of this plugin, it definitely something that could be looked in to, in the future.

**Comment by ADRFranklin** [comment]
Sorry, as you can tell by the name of the include, this only applies to weapon damages, and damage dealt.

**Comment by InterSstellar** [comment]
Your Work Is Awesome.
Can You Please Release An AC System Based On A Plugin Like SKY That Detects Fly Hacks, Car Fly Hacks, Teleport, And Some More Please? Cuz Your Include And Plugin Is Awesome I Know You Can Make A Great AC System. I Hope You Make It One Day :(

**Comment by ADRFranklin** [comment]
This is more a SKY question then weapon-config, and also I am already planning an Anticheat written in C++. But I have a few more projects I have to go done before I can continue with it.

**Comment by Zorono** [comment]
@InterSstellar https://forum.sa-mp.com/showthread.php?p=2695108
