### ISSUE TITLE
undefined symbol "FreezeSyncPacket"

### ISSUE THREAD

**Issue by elvianod982** [oscar-broman/samp-weapon-config#122]
With a stock version of the latest weapon-config.inc, I'm unable to compile and getting:

\pawno\include\weapon-config.inc(2208) : error 017: undefined symbol "FreezeSyncPacket"
\pawno\include\weapon-config.inc(2208) : warning 215: expression has no effect
\pawno\include\weapon-config.inc(2208) : error 001: expected token: ";", but found ")"
\pawno\include\weapon-config.inc(2208) : error 029: invalid expression, assumed zero
\pawno\include\weapon-config.inc(2208) : fatal error 107: too many error messages on one line

Compilation aborted.

Pawn compiler 3.10.9	 	 	Copyright (c) 1997-2006, ITB CompuPhase

4 Errors.

**Comment by ADRFranklin** [comment]
Please update your version of SKY
https://github.com/oscar-broman/SKY/releases/tag/2.3.0

and make sure to download a new version of the include:
https://github.com/oscar-broman/SKY/blob/master/SKY.inc

**Comment by Xarison** [comment]
After connecting include weapon-config > Stack/heap size:      16384 bytes; estimated max. usage: unknown, due to recursion
