### ISSUE TITLE
Alter Healthpoints

### ISSUE THREAD

**Issue by izrie1** [oscar-broman/samp-weapon-config#124]
How can I alter HP so that players can have more than 100hp? It doesn't work it seems with SetPlayerHealth.

**Comment by ADRFranklin** [comment]
You can use these to change the max values a player can have
```
stock SetPlayerMaxHealth(playerid, Float:value);
stock SetPlayerMaxArmour(playerid, Float:value);
```

then you can you use `SetPlayerHealth and `SetPlayerArmour` to those max values.

**Comment by ADRFranklin** [comment]
@izrie1 Did you solve your issue yet?
