### ISSUE TITLE
SetPlayerTeam and explosions not affecting vehicles

### ISSUE THREAD

**Issue by TamerGezici** [oscar-broman/samp-weapon-config#128]
Hello,

So I am currently using an outdated version, maybe this was fixed by a future update, I dont know. I can try upgrading later.

But anyways, I use SetPlayerTeam on my script to set teams. When I do this players can not damage vehicles through explosions

You can try this yourself. Make a command to set a players team using SPT function. Then set yourself to team 0 and the other player to 1. Make the other player enter a car. Throw the grenade to the car or shoot at it with a tank. The car wont get damaged. 

How can this be solved?

**Comment by TamerGezici** [comment]
The same issue is valid for rustler gun. It doesnt damage enemy vehicles.

**Comment by AliLogic** [comment]
The problem is that you have vehicle friendly fire enabled most probably,  and since this library (include) sets the players team to the same one team to negate the damage, disabling this allow you to damage your enemy vehicles but also your team vehicles too using Rhino etc.
