### ISSUE TITLE
Shallow Water - No Damage (Screenshot Included)

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#13]
Damage is (usually) not taken when falling into water from a high height. Sometimes it does kill me, most of the time the debug messages only show OnPlayerTakeDamage. Falling anywhere on land does call other functions, but in shallow (not too shallow, but shallow enough to call OnPlayerTakeDamager) water nothing else is called. I think it only happens when the damage taken is 165.0 (aka Splat Damage.)

![sa-mp-145](https://cloud.githubusercontent.com/assets/9919010/6240649/46599a26-b6df-11e4-9bdf-73ca3f7e68e6.png)

**Comment by Crayder** [comment]
Well it may not be just the shallow water, as seen below it failed three times, twice on the ground. The last one (100.0) was actually in the water.
![sa-mp-147](https://cloud.githubusercontent.com/assets/9919010/6241796/8dfd11de-b6f1-11e4-9991-3ce47193464a.png)

**Comment by oscar-broman** [comment]
The custom fall damage basically checks for animation changes and velocity changes.

You can see what it does in `OnPlayerUpdate`.

If you add the swim animations, you should be able to get them to cause damage. How much does the velocity change when you hit water?

**Comment by Crayder** [comment]
I can't test until tomorrow, I'll edit this comment when i test it.

**Comment by oscar-broman** [comment]
Better post a new comment whenever you've got updates - GitHub doesn't send notifications for edited comments.

**Comment by Crayder** [comment]
It's not just water.
![image](https://cloud.githubusercontent.com/assets/9919010/6248534/9be67ecc-b74e-11e4-9595-2eeadb183cab.png)
The amount is always 165.0 when the bug occurs.

**Comment by Crayder** [comment]
I think it may have something to do with OnPlayerUpdate, but I don't see how. In OPU, you check to see if the velocity is less than -0.2. In the screenshots you can see that the velocities in OPU are only -0.1, that is only when the anim's change. Even though the amount of damage taken is more than zero, the InflictDamage for collision damage is never called in OPU. I'll do some debugging real quick and come back...

**Comment by oscar-broman** [comment]
Basically, I made a custom damage system that completely ignores the damage reported in `OnPlayerTakeDamage`. I must admit I didn't thoroughly test it and it should still be considered an experimental feature.

Currently, the custom damage will check for an animation index change then measure the Z velocity diff.

I think the best way to improve this is add the same velocity measuring logic in `OnPlayerTakeDamage` for `WEAPON_COLLISION`, then inflict damage in both places and ignore subsequent damage within, say, 150ms.

I'll be verbose just for the sake of getting my point across properly. For example, this is how a fall could look:

1. 0ms - Player hits the ground
2. 100ms - `OnPlayerTakeDamage` - velocity measured and damage inflicted
3. 200ms - fall detected in `OnPlayerUpdate` - ignored

Or this:

1. 0ms - Player hits the ground
3. 100ms - fall detected in `OnPlayerUpdate` - damage inflicted
2. 200ms - `OnPlayerTakeDamage` - ignored

Or this:

1. 0ms - Player hits the ground
3. 100ms - fall detected in `OnPlayerUpdate` - damage inflicted

Or this:

1. 0ms - Player hits the ground
2. 100ms - `OnPlayerTakeDamage` - velocity measured and damage inflicted

**Comment by Crayder** [comment]
Well, when the velocity is less than -2 it works in OnPlayerUpdate. Are you saying you would check in both OPTD and OPU? That would make sense. If it fails in one but occurs in the other, pass. What if it passes both? Failing both would obviously be nothing.

**Comment by oscar-broman** [comment]
If it fails both, the logic in `OnPlayerUpdate` needs to be improved to detect whatever is causing it to fail.

**Comment by Crayder** [comment]
Well I'm about to debug and see where it stops, if the problem is in OPU I'll see it.

**Comment by oscar-broman** [comment]
I'm too busy, sorry. I won't have much time for a couple weeks, at least not to test things in-game.

**Comment by Crayder** [comment]
Anyways, here is the debug console:
![image](https://cloud.githubusercontent.com/assets/9919010/6258102/cba779be-b793-11e4-87e1-e08956d717ec.png)
But here is the code:

		if (anim != s_LastAnim[playerid]) {
			new prev = s_LastAnim[playerid];
			s_LastAnim[playerid] = anim;

			if (((prev == 1130 && vz == 0.0) || 1128 <= anim <= 1134 || anim == 1208)) {
				new Float:amount = -1.0;
				DebugMessage(playerid, "vz: %f anim: %d prev: %d", vz, anim, prev);

				vz = s_LastZVelo[playerid];

				printf("[before] amount: %0.2f", amount);
				if (vz <= s_FallDeathVelocity) {
					amount = 0.0;
					printf("[<= falldeathvelocity] amount: %0.2f", amount);
				} else if (vz <= -0.2) {
					if (vz == -0.2) {
						amount = s_WeaponDamage[WEAPON_COLLISION] * 0.2;
						printf("[vz = -0.2] amount: %0.2f", amount);
					} else {
						amount = (vz + 0.2) / (s_FallDeathVelocity + 0.2);
						amount *= s_WeaponDamage[WEAPON_COLLISION];
						printf("[vz ! -0.2] amount: %0.2f", amount);
					}
				}
				printf("[after] amount: %0.2f", amount);

				if (amount >= 0.0) {
					DebugMessage(playerid, "fall dmg: %.5f (vz: %f, anim: %d, prev: %d)", amount, vz, anim, prev);

					InflictDamage(playerid, amount, INVALID_PLAYER_ID, WEAPON_COLLISION, 3);

					if (amount == 0.0) {
						amount = s_PlayerHealth[playerid];
					}
				}
			}
			else printf("[else] lastvz: %0.2f", s_LastZVelo[playerid]);
		}
		
That is exactly what you have under OPU, but with debug messages. None of those messages are in the console.

**Comment by oscar-broman** [comment]
When you fall on the ground, your velocity will go to 0 instantly. When you hit the water, however, it will gradually lower.

That makes it a bit harder. Does `OnPlayerTakeDamage` get called every time? Otherwise you will need to make a bit more complicated code to detect the fall.

**Comment by oscar-broman** [comment]
If you want to detect fall damage into water and possibly also shallow water (unless `OnPlayerTakeDamage` always is called) this is how you would go about doing that:

1. Make an array to store the last N z-velocities. Let's say 10. Something like this:

  ```pawn
new Float:s_PrevVZ[MAX_PLAYERS][10];
// fill with 0.0 OnPlayerConnect
new s_PrevVZI[MAX_PLAYERS]; // the current position in the array above
// fill with 0 on OnPlayerConnect
  ```
2. Every time Z velocity changes in `OnPlayerUpdate`, save it.

  ```pawn
public OnPlayerUpdate(playerid) {
    new Float:vx, Float:vy, Float:vz;
    GetPlayerVelocity(playerid, vx, vy, vz);
    if (s_PrevVZ[playerid][s_PrevVZI[playerid]] != vz) {
        new idx = (s_PrevVZI[playerid] + 1) % sizeof(s_PrevVZ[]);
        s_PrevVZI[playerid] = idx;
    }
  ```
3. When a swim animation is detected (this will HOPEFULLY work), loop s_PrevVZ and get the highest velocity down (i.e. the lowest value).

**Comment by Crayder** [comment]
Well actually none of the messages I put in OnPlayerUpdate are sent, even debug messages. 

![image](https://cloud.githubusercontent.com/assets/9919010/6259227/23138fd0-b79e-11e4-9b79-69671876384f.png)

**Comment by oscar-broman** [comment]
Clearly something has to be wrong there - you see the other messages but not the first ones.

Sure you reloaded the script and all that? Try just putting a `printf` statement both in `ScriptInit` and `OnPlayerUpdate`.
