### ISSUE TITLE
DebugMessage* macros - error 036: empty statement

### ISSUE THREAD

**Issue by Hoxxy** [oscar-broman/samp-weapon-config#130]
This error appears at all places where DebugMessage* macros are used.

The only solution I found is to remove all semicolons at places where the macros are used or just comment out those lines and not use them at all.

**Comment by ADRFranklin** [comment]
You need to define a value for the define
so not this 
```
#define WC_DEBUG
```

but this
```
#define WC_DEBUG true
```
