### ISSUE TITLE
Not taking damage from explosions/fire/drowning

### ISSUE THREAD

**Issue by SrMilton** [oscar-broman/samp-weapon-config#132]
Server debug: 
![image](https://user-images.githubusercontent.com/35127424/78277462-f2a09180-74ea-11ea-9892-06edbafe95cd.png)

Ingame:
![sa-mp-918](https://user-images.githubusercontent.com/35127424/78277540-1663d780-74eb-11ea-8c58-09131fedc9fb.png)

I've already tried something like this:
![image](https://user-images.githubusercontent.com/35127424/78277835-85d9c700-74eb-11ea-8044-20e062b1358d.png)

Any ideias?

**Comment by ADRFranklin** [comment]
Would be nice if you could explain in full detail what you are trying to accomplish here?

**Comment by SrMilton** [comment]
The problem is: I'm not taking damage from explosions and idk why (I want this damage), idk what I did wrong, any ideas of what i can change to fix that ? As you can see on SS from the game, my life still in 100.

**Comment by ADRFranklin** [comment]
You must have altered the damage incorrectly negating it, or you have returned 0 somewhere and prevented the damage being applied.

Please make sure you check any other libraries or your own code for modifying OnPlayerDamage and as well as modifying values in OnPlayerTakeDamage and OnPlayerGiveDamage.

**Comment by SrMilton** [comment]
The problem was something on OnPlayerDamage, i fixed it checking if issuerid != invalid player id
![image](https://user-images.githubusercontent.com/35127424/78458225-151ae200-7686-11ea-927c-aecb18d4ff9d.png)

Ty
