### ISSUE TITLE
Infinity health for Admin Duty

### ISSUE THREAD

**Issue by SaboT94** [oscar-broman/samp-weapon-config#135]
Hello, how can i bypass maximum health on 100.0, to get my Admin god mode when on duty.. i tryed with SetHp 100+ but it keep resetting on 100. Thanks...

**Comment by Zorono** [comment]
https://github.com/oscar-broman/samp-weapon-config/issues/124#issuecomment-585635150

**Comment by SaboT94** [comment]
Thanks man...

**Comment by Jeroen52** [comment]
@SaboT94 You can also prevent the admin from receiving damage while the admin is on admin duty.

Something simple like this should work in `OnPlayerDamage`.
```
	if(AdminDuty[playerid])
		return 0;
```

**Comment by SaboT94** [comment]
Thanks for info Jeroen52,

i did it in admin duty cmd

`SetPlayerMaxHealth(playerid, 0x7FFFFFFF);
SetPlayerMaxArmour(playerid, 0x7FFFFFFF);
SetPlayerHealth(playerid,0x7FFFFFFF);
SetPlayerArmour(playerid,0x7FFFFFFF);`

and when going off i set 100 and 0.

return 0; OnPlayerDamage blocking every damage? even falling? minugun spray, explosion?... that is good for like /god mode?
