### ISSUE TITLE
OnPlayerGiveDamage problem 

### ISSUE THREAD

**Issue by PT-Player** [oscar-broman/samp-weapon-config#136]
Hello im having a problem look:

https://pastebin.com/89R09UbG

I think is a new hack my MAX_PLAYERS is 215

Thanks!!

**Comment by ADRFranklin** [comment]
How recent is your weapon-config? Also I am going to need a lot more details to even consider going forward, I don't want to be changing code if it ends up having nothing to do with the initial issue.

**Comment by PT-Player** [comment]
is the last version... the problem i think is dont have a check on OnPlayerGiveDamage if the damagedid is connected or not..

but not sure..

**Comment by PT-Player** [comment]
@ADRFranklin give a fix for this on discord maybe consider add it..
