### ISSUE TITLE
OnPlayerDeath (Vehicle explode)

### ISSUE THREAD

**Issue by SaboT94** [oscar-broman/samp-weapon-config#141]
Hello, 

https://github.com/oscar-broman/samp-weapon-config/issues/35

https://github.com/oscar-broman/samp-weapon-config/issues/32

Is this problem solved with newer version? I mean... this is 4 years old issue.

I still have some hangs when dying in vehicle explode (SOMETIMES), it's force respawning 2 times, and respawn me in GSF by default coordinates like when pressed F4 selection class..

EDIT; Can i put some delay to spawn? Like when he dies in explode like delay of respawning like 2-3 sec, like death animation without include.

EDIT: Sometimes works, even death animation, sometimes instant Respawn, oh god... i have latest include btw and latest sky...

**Comment by izrie1** [comment]
I confirm this issue. Facing this as well
