### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ramires7** [oscar-broman/samp-weapon-config#143]
When the player dies while driving a vehicle, the death animation is applied, but the vehicle is left with a "ghost driver". However, if the player presses F, an animation of the player exiting the vehicle is applied. How to solve this?
Ps: The player does not spawn, only animation is applied.
(I'm using the https://github.com/oscar-broman/samp-weapon-config/pull/127/files/b317381bfdc07c7b099182f04e426bd6f1ada009 version). #127 #

**Comment by ADRFranklin** [comment]
Can you confirm if this happens on the master branch? or is it specific to this branch?

**Comment by ramires7** [comment]
Only in this branch.

**Comment by ramires7** [comment]
> 
> 
> Can you confirm if this happens on the master branch? or is it specific to this branch?

Only in this branch.

**Comment by ADRFranklin** [comment]
So remind me what happens in the master branch when this happens?

**Comment by ramires7** [comment]
> 
> 
> So remind me what happens in the master branch when this happens?

Player respawn.
