### ISSUE TITLE
Die By Vehicle explode Problem

### ISSUE THREAD

**Issue by InterSstellar** [oscar-broman/samp-weapon-config#145]
Hi When Someone Die In by vehicle explode Sometimes There is No Problem And He Spawns Normally but sometimes He Spawns Twice And When He Spawns For The Second Time `OnPlayerSpawn` Doesn't Call Even In Weapon-config.inc. And He Spawn With A Cigar Or A Bottle Of Drink And He Can Run Like Cj Even When I Didn't Use `UsePlayerPedAnims()`

And The Worse Part Of That Is He Will Kick By Anti Cheat Cuz The AC Is Included After WC And `OnPlayerSpawn` Doesn't Called. =((((((

I Am Using YSF And Pawn-Memory Plugins Too I Don't Know If YSF Cause The Problem I Am Going To Check. Cuz When I Didn't Use `UsePlayerPedAnims` How The Player Can Run Like Cj?

Meybe Its A SA-MP Client Bug

I Hope I Was Right And Sorry For My Bad English. :((

**Comment by InterSstellar** [comment]
I Removed YSF But The Problem Didn't Fixed =(((

Note: I'm Using Nex-Ac Too !

**Comment by InterSstellar** [comment]
After A Lot Of Testing At This Time i am 100% Sure That Is A Client SA-MP Bug That Cause By WC But How To Fix It? =((

**Comment by InterSstellar** [comment]
Can Someone Tell Me Please How WC Respawns The Player After Death?
I Only Found This:
```
TogglePlayerSpectating(playerid, true);
TogglePlayerSpectating(playerid, false);
```
So I Removed Them To Test But it Respawns Me immediately After Hitting A Building Hard With A Jet (520)

**Comment by ADRFranklin** [comment]
Which branch are you using? master or fix-hooks?

**Comment by InterSstellar** [comment]
@ADRFranklin  Master

**Comment by InterSstellar** [comment]
@ADRFranklin 
I'm Using Master Branch
If You Fixed it In fix-hooks branch Thank You Very Much But It Will Be Great If You Also Fix Vehicle Friendly Fire Too in that branch Cuz It just fixed only In master branch And I Need It So Bad =((

**Comment by TamerGezici** [comment]
Actually @ADRFranklin I would very much appreciate it if you could merge master into fix-hooks branch so the fix-hooks branch is updated? Then I can put it live on my server to test whether if there are any issues with it.

**Comment by ADRFranklin** [comment]
@TamerGezici I have rebased it on it, so it is up to date now.

**Comment by ADRFranklin** [comment]
@TamerGezici @InterSstellar Can you guys checkout the latest changes from the `hooks-fix-2` branch?

**Comment by InterSstellar** [comment]
For Sure ! But Please Give Me Some Time For That Cuz I Need To Modify WC To Work With Nex-AC For My Server and i have something else to do ;D
