### ISSUE TITLE
Vehicle friendly fire

### ISSUE THREAD

**Issue by RodrigoMSR** [oscar-broman/samp-weapon-config#146]
Players can damage teammate's vehicles (onfoot or with Hunter/Hydra etc.). I have not found any function to disable this.

**Comment by AliLogic** [comment]
Are you using the master branch and the latest version of the weapon config?  Please confirm.  This was fixed.

**Comment by RodrigoMSR** [comment]
Yes.

I called SetPlayerTeam on WC_SetPlayerTeam and it looks like it fixed the problem (I don't know if this can cause bugs).

**Comment by RodrigoMSR** [comment]
I noticed that the bug was actually fixed, however the team is updated in OnPlayerSpawn, when using SetPlayerTeam the player's team is not updated in the same moment.

**Comment by AliLogic** [comment]
Alright.  It just might the way I am using stuff in my script I was not able to reproduce such bug.  I will make a PR.  Thanks a lot man.
