### ISSUE TITLE
Unused assignment

### ISSUE THREAD

**Issue by Daniel-Cortez** [oscar-broman/samp-weapon-config#149]
In function `OnPlayerUpdate` the following code looks suspicious:
https://github.com/oscar-broman/samp-weapon-config/blob/998ab71baac695e3dd30d433f8c50257c8003f15/weapon-config.inc#L3055-L3057
The assignment `amount = s_PlayerHealth[playerid];` seems to be unused upon return. You'll probably want to remove that line (and the whole `if` statement with it).

Discovered with the following experimental feature: https://github.com/pawn-lang/compiler/pull/480

**Comment by ADRFranklin** [comment]
Thanks for report, will look at that.
