### ISSUE TITLE
(error) argument type mismatch (argument 2)

### ISSUE THREAD

**Issue by gfalqui** [oscar-broman/samp-weapon-config#160]
Installing the latest release of the include throws an error.

game_1      | failed to prepare: build failed, can not run
game_1      | /data/dependencies/samp-weapon-config/weapon-config.inc:4798 (error) argument type mismatch (argument 2)
game_1      | /data/gamemodes/sap.pwn:1250 (warning) function "WC_OnPlayerDamageDone" should return a value

**Comment by ADRFranklin** [comment]
The const parameter was removed from `OnPlayerPrepareDeath` and you should simply return a value for the other issue.
