### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by TahaR9** [oscar-broman/samp-weapon-config#168]
I am unable to compile the latest release of weapon-config. Here are the errors I am getting at compilation:

```
C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(1589) : error 035: argument type mismatch (argument 2)
C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(2235) : error 017: undefined symbol "FreezeSyncPacket"
C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(2235) : warning 215: expression has no effect
C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(2235) : error 001: expected token: ";", but found ")"
C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(2235) : error 029: invalid expression, assumed zero
C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(2235) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase


5 Errors.
```

**Comment by elvianod982** [comment]
Please update your version of SKY
https://github.com/oscar-broman/SKY/releases/tag/2.3.0

and make sure to download a new version of the include:
https://github.com/oscar-broman/SKY/blob/master/SKY.inc

**Comment by TahaR9** [comment]
> Please update your version of SKY
> https://github.com/oscar-broman/SKY/releases/tag/2.3.0
> 
> and make sure to download a new version of the include:
> https://github.com/oscar-broman/SKY/blob/master/SKY.inc

Thanks, I just did, but still getting one error:

```C:\ZOMBIE\ZS\pawno\include\weapon-config.inc(1589) : error 035: argument type mismatch (argument 2)```
