### ISSUE TITLE
Passengers being able to inflict damage from heliblades

### ISSUE THREAD

**Issue by ADRFranklin** [oscar-broman/samp-weapon-config#169]
After testing for a while, I have come across an issue where passengers are detected for giving damage to a player when they are killed via heliblades. Only the vehicle's driver should be responsible for giving the damage and all damage from passengers should be ignored.

If anyone can help me by testing this themselves, and reporting back then I can confirm it as being an issue that affects everyone.

**Comment by ADRFranklin** [comment]
It's probably safe enough to simply add a check to `OnPlayerTakeDamage` to check if the issuerid is in a vehicle and not the driver and return early.

Something like
```
		new pstate = GetPlayerState(playerid);

		// https://github.com/oscar-broman/samp-weapon-config/issues/104
		if(weaponid == WEAPON_VEHICLE
		|| weaponid == WEAPON_CARPARK
		|| weaponid == WEAPON_HELIBLADES) {
			if(!IsPlayerInAnyVehicle(issuerid) || pstate != PLAYER_STATE_DRIVER) {
				return 0;
			}
		}
```

If anyone wants to double check this, by making the changes themselves, then please report back on your experiences.

**Comment by NexiusTailer** [comment]
Fixed too
