### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Pabloz10** [oscar-broman/samp-weapon-config#178]
error 017: undefined symbol "_ALS"
error 017: undefined symbol "_ALS_go"
error 029: invalid expression, assumed zero

When trying to compile with weapon-config include. 

the line is: OnPlayerSpawn(playerid); , if i remove it, the error move on next OnPlayerSpawn(playerid);

I used weapon-config in 2018 on same gamemode but it worked.
Now i'm using last version of SKY , last version of weapon-config.

I tried weapon-config on another gamemodes, but the same error appear.

I updated server includes too.

**Comment by Y-Less** [comment]
Is this line in weapon-config or your own code?  It looks like `OnPlayerSpawn` is being called directly as a function, instead of as a callback.

**Comment by Pabloz10** [comment]
The error line is in my own code and that's right , it's being called as a function.
I use OnPlayerSpawn instead of SpawnPlayer when i want to respawn a player. I've noticed it's a faster respawn and the 'bottle in hand' bug it's avoided. I don't know if i use it wrong but i didn't had problems before.
With older versions of weapon-config it works, but the latest version with Pre-hooks for hooking callbacks it shows me the error.

**Comment by Y-Less** [comment]
If you know it is wrong, don't do it.

**Comment by ADRFranklin** [comment]
@Pabloz10 Do not call callbacks directly, instead use `CallLocalFunction` (recommended) or `CallRemoteFunction` to call the callbacks properly.

**Comment by Pabloz10** [comment]
Thanks!
