### ISSUE TITLE
Problem with save stats

### ISSUE THREAD

**Issue by Derky340** [oscar-broman/samp-weapon-config#180]
Hello i want to put include weapon-config in admin FS for some reason
But when i put in FS ADMIN the include causes me problem with stats save all ( adminlevel,kills,deaths) saves not work
when i reconnect i get register dialog and not login dialog .. ? what cause this problem ?

**Comment by Derky340** [comment]
???

**Comment by ADRFranklin** [comment]
weapon-config was not designed to work in a filterscript, it uses "CallLocalFunction" which is limited to your current script, compared to "CallRemoteFunction" so nothing will work across scripts.

Please instead adapt it to work in your gamemode.
