### ISSUE TITLE
Vehicle fall, drowning and explosion

### ISSUE THREAD

**Issue by wearLyS** [oscar-broman/samp-weapon-config#181]
https://www.youtube.com/watch?time_continue=3&v=Nb_HDy4cw2U&feature=emb_title

According to the video, the player is not receiving damage or dying in the following situations: fall, drowning, vehicle explosion.

**Comment by ADRFranklin** [comment]
This seems completely the fault of how you have setup weapon-config, I can confirm that on multiple servers, that dying from fall damage, drowning and even dying in a helicopter all happen. 

Now I can't say what is going on here, as lots of people modify their versions of weapon-config without making an issue here and asking for a proper implementation of it.

All I can say here is that, I am going to need a lot more information to even attempt to debug what is going on.

**Comment by wearLyS** [comment]
I managed to solve the problem!
