### ISSUE TITLE
Best configuration

### ISSUE THREAD

**Issue by xRadical3** [oscar-broman/samp-weapon-config#182]
Can you provide the best configuration for lagcomp ON?

This is my configuration but not good:

```
public OnGameModeInit()
{
    //Weapon Configuration

    SetVehiclePassengerDamage(true);
    SetDisableSyncBugs(true);
    SetRespawnTime(3000);
    SetWeaponDamage(WEAPON_CHAINSAW, DAMAGE_TYPE_STATIC, 2.5, 2.0, 1.0);
    SetWeaponDamage(WEAPON_M4, DAMAGE_TYPE_STATIC, 4.0, 10.0, 3.0, 15.0, 2.0, 50.0, 1.5, 100.0);
    SetWeaponDamage(WEAPON_AK47, DAMAGE_TYPE_STATIC, 3.5, 10.0, 3.0, 15.0, 2.5, 50.0, 1.0, 100.0);
    SetWeaponDamage(WEAPON_SAWEDOFF, DAMAGE_TYPE_STATIC, 4.0, 25.0, 3.0, 35.0, 2.5, 50.0, 2.0, 100.0);

    SetWeaponMaxRange(WEAPON_CHAINSAW, 2.0);
    SetWeaponMaxRange(WEAPON_M4, 200.0);
    SetWeaponMaxRange(WEAPON_AK47, 200.0);
    SetWeaponMaxRange(WEAPON_SNIPER, 300.0);
    SetWeaponMaxRange(WEAPON_SAWEDOFF, 50.0);

    //------------------
```

I do not know what to do to make the chainsaw less damaging to players.
SetWeaponDamage(WEAPON_CHAINSAW, DAMAGE_TYPE_STATIC, 2.5, 2.0, 1.0);
I changed the Chainsaw damage, but it damages the player more and the player dies within 3 seconds.
This problem is also present in the Sawn-Off Shotgun weapon, which kills the player with 2 shots.

**Comment by ADRFranklin** [comment]
I think the chainsaw issue has been fixed the recent patch done by @NexiusTailer so you might have better luck with it now.
