### ISSUE TITLE
problem with healthbar

### ISSUE THREAD

**Issue by aquaman21** [oscar-broman/samp-weapon-config#183]
I'm facing this issue with the include. The original health bar shows behind the healthbar created by include. https://i.imgur.com/dW4ylmt.png
Someone suggested me that I should try removing my textdraws in gamemode and then check it again but that gave the same result. Didn't fix the problem.

**Comment by ADRFranklin** [comment]
This happens when you use widescreen fix or mods that modify resolutions aspects. You can try remove them for now, but that is only a temp solution. A better solution is for us to find a better way to display it, which we will do in the future.

**Comment by NexiusTailer** [comment]
Is it related to issue #165  and were fixed in #195 ?

**Comment by ADRFranklin** [comment]
Yes it is, I would suppose.
