### ISSUE TITLE
redefinition of constant/macro (symbol "SetPlayerHealth")

### ISSUE THREAD

**Issue by TerzicScript** [oscar-broman/samp-weapon-config#184]
Just added weapon-config and SKY to my script, and there are 2 warnings : 

`\include\weapon-config.inc(5799) : warning 201: redefinition of constant/macro (symbol "SetPlayerHealth")
\include\weapon-config.inc(5823) : warning 201: redefinition of constant/macro (symbol "SetPlayerArmour")`

Also, line of code in weapon-config is : 

`#if defined _ALS_SetPlayerHealth
	#undef SetPlayerHealth
#else
	#define _ALS_SetPlayerHealth
#endif
#define SetPlayerHealth WC_SetPlayerHealth //this one

#if defined _ALS_SetPlayerArmour
	#undef SetPlayerArmour
#else
	#define _ALS_SetPlayerArmour
#endif
#define SetPlayerArmour WC_SetPlayerArmour //this one`

I should also say that everything works normally, like setting hp with command, setting armor, falling and losing hp etc..

**Comment by TerzicScript** [comment]
Problem was with OnPlayerShootPlayer include which also defined SetPlayerHealth...

**Comment by Y-Less** [comment]
Which means that that include isn't using ALS correctly.  ALS is designed to allow different includes to work together without causing these conflicts.  weapon-config does it correctly, as you can see from the code you posted, which means you need to open an issue on the other library to tell them about the problem.
