### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Kevb312** [oscar-broman/samp-weapon-config#186]
I deployed the library on my server, it is an excellent tool.
however I have some issues which I will describe below:

I have a / kill command but it doesn't work, this is the code:

`CMD:kill(playerid)` 
{
	if(team[playerid]` == TEAM_RED || team[playerid] == TEAM_BLUE)
	{
	SetPlayerHealth(playerid,0.0);
	  }
return 1;

}

I have no idea why this is happening.
Another question I have is, how can I set the respawn location? When a player reappears, they do so in the predetermined area (las venturas) and not in the location that I tell them.
Could you help me? Thanks a lot

**Comment by NexiusTailer** [comment]
> Another question I have is, how can I set the respawn location? When a player reappears, they do so in the predetermined area (las venturas) and not in the location that I tell them.
> Could you help me? Thanks a lot

Are you tried SetSpawnInfo? Also check if you have any SetPlayerPos in your OnPlayerSpawn callback, maybe this is the reason of such behaviour, if it is found there.

**Comment by ADRFranklin** [comment]
I'm going to need more information about what you are trying to do, it's not straight forward enough for me to give a conclusive answer. Please provide more details about the way you are using, what you have tried to do, and what you expect the outcome to be.

**Comment by AsfandSoomro** [comment]
_SetPlayerHealth(playerid, -1.0);_ (If it is in Gamemode, otherwise you can make public function call it in your filterscript)
Kills the player instantly.
