### ISSUE TITLE
Native healthbar

### ISSUE THREAD

**Issue by FeelipeSilva** [oscar-broman/samp-weapon-config#187]
Hello, I would like to disable the healthbar created by include. Because it is bugging for players who use another hud, mobiles and for those who use another solution. I tried to use the EnableHealthBarForPlayer, but he just removed the textdraw and the native healthbar is full, can anyone help me?

**Comment by NexiusTailer** [comment]
If you want to switch into original health system then you will be forced to use original (clientside) death system too. That means you could not set custom damage for some damage reasons like falling from the sky and some other things. Moreover there will be some additional (maybe random) problems related to samp bugs with death/spawn system like spawning with cigarette in hands, after-death desync when you appear "dead" with 0.0 hp for others but keep alive and being able to run for yourself etc.
