### ISSUE TITLE
Improved sanity checking for passenger/driver DB

### ISSUE THREAD

**Issue by oscar-broman** [oscar-broman/samp-weapon-config#2]
Make sure the shots fired are legit.

**Comment by Crayder** [comment]
Also, add detection for drive by to passenger only vehicles (and unoccupied). Currently doing a drive by the vehicle with passenger only is unaffected.

**Comment by oscar-broman** [comment]
I'm not sure if driver drive-by fires `OnPlayerWeaponShot` - if not, it will be very hard to enable passenger-only/unoccupied vehicle damage.

**Comment by oscar-broman** [comment]
#12
