### ISSUE TITLE
Fall problem

### ISSUE THREAD

**Issue by raedman90** [oscar-broman/samp-weapon-config#203]
My server is not counting crash damage, can someone help me?

Plugin SKY 2.2.2
weapon-config last version.

A versão mais atual do plugin faz com que o meu servidor desligue

**Comment by ADRFranklin** [comment]
What is crash damage?

**Comment by YellowSunZ** [comment]
@raedman90 Você já arrumou seu problema? Sofri com o mesmo problema no meu código porém já resolvi.
Se precisar de ajuda ainda pode me chamar no discord YellowSunZ#0404

**Comment by YellowSunZ** [comment]
Acabei de ver a sua resposta aqui.
Eu enviei o que possivelmente resolveria seu problema. 
Não recebi seu retorno então não sei se te ajudou ou não.
Espero ter ajudado!
