### ISSUE TITLE
Problem Team shot team dont work

### ISSUE THREAD

**Issue by Nung0141** [oscar-broman/samp-weapon-config#205]
//public OnPlayerTakeDamage(playerid, issuerid, Float: amount, weaponid, bodypart) 
public OnPlayerDamage(&playerid, &Float:amount, &issuerid, &weapon, &bodypart)
{ 
	if(issuerid == INVALID_PLAYER_ID) return 1;	
    if(issuerid != INVALID_PLAYER_ID) 
    { 
		printf("debug 3 %s %s", PlayerShotPlayer[issuerid][playerid] = 1);
        PlayerShotPlayer[issuerid][playerid] = 1; 
		UpdateXPTextdraw(playerid);
        new Float:HP;
        GetPlayerHealth(playerid, HP);
		if(pteam[issuerid] == TEAM_HUMAN)
		{
			if(pteam[playerid] == TEAM_HUMAN)
			{
				if(weapon == 0)
				{
					SetPlayerHealth(issuerid, HP - 15);
					GameTextForPlayer(issuerid,"~r~DO NOT ACCTACKER YOUR TEAM",6000,4);
					printf("debug 2 %s %s",pteam[issuerid] == TEAM_HUMAN,pteam[playerid] == TEAM_HUMAN);
				}
			}
		}
		
		printf("debug");

**Comment by ADRFranklin** [comment]
You are supposed to `return 0;` inside OnPlayerDamage if you don't want damage to be inflicted
