### ISSUE TITLE
Server restarting

### ISSUE THREAD

**Issue by PazzOnee** [oscar-broman/samp-weapon-config#208]
When i use latest version of weapon-config.inc server do restarting and i got log in mysql log folder
logs/log-core.log

[07/21/21 21:30:31] [ERROR] signal 11 (SIGSEGV) catched; shutting log-core down (errno: 0, signal code: 1, exit status: 0)

**Comment by elvianod982** [comment]
I can confirm this with the latest version of weapon-config. Nothing was logged to server_log.txt or the screen session that the samp03svr process was running in.

Should I consider enabling debug mode?

@ADRFranklin

**Comment by ADRFranklin** [comment]
Without some crashdetect logs showing the crash, there is not a lot here for me to go off and debug.

**Comment by elvianod982** [comment]
I see mention of SendLastSyncPacket. Maybe https://github.com/oscar-broman/samp-weapon-config/commit/4012a02ce149d414d64047064957b8ef4948dd6f caused this?

23/07/2021 18:38:49 [debug] Server crashed while executing server.amx
23/07/2021 18:38:49 [debug] AMX backtrace:
23/07/2021 18:38:49 [debug] #0 native SendLastSyncPacket () in SKY.so
23/07/2021 18:38:49 [debug] #1 000d5e18 in ?? (2) in server.amx
23/07/2021 18:38:49 [debug] #2 000d4dcc in ?? (2, 0) in server.amx
23/07/2021 18:38:49 [debug] #3 000da214 in ?? (2, 1092511334, 3, 31, 9, 0) in server.amx
23/07/2021 18:38:49 [debug] #4 000cf7f4 in public ac_OnPlayerGiveDamage (3, 2, 1092511334, 31, 9) in server.amx
23/07/2021 18:38:49 [debug] #5 00035914 in public OnPlayerGiveDamage (3, 2, 1092511335, 31, 9) in server.amx
23/07/2021 18:38:49 [debug] Native backtrace:
23/07/2021 18:38:49 [debug] #0 f6c3ef7f in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] #1 f6c3781d in _ZN11CrashDetect20PrintNativeBacktraceERSoRKN2os7ContextE () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] #2 f6c37e48 in _ZN11CrashDetect20PrintNativeBacktraceERKN2os7ContextE () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] #3 f6c395dc in _ZN11CrashDetect7OnCrashERKN2os7ContextE () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] #4 f6c3e79f in ?? () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] #5 f7f60b70 in __kernel_rt_sigreturn () in linux-gate.so.1
23/07/2021 18:38:49 [debug] #6 f67b429e in ?? () in plugins/SKY.so
23/07/2021 18:38:49 [debug] #7 f67bab6c in ?? () in plugins/SKY.so
23/07/2021 18:38:49 [debug] #8 f67b8d2f in ?? () in plugins/SKY.so
23/07/2021 18:38:49 [debug] #9 f67b8ebb in ?? () in plugins/SKY.so
23/07/2021 18:38:49 [debug] #10 080950e4 in ?? () in ./samp03svr
23/07/2021 18:38:49 [debug] #11 f6c3746f in _ZN11CrashDetect15ProcessCallbackEiPiS0_ () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] #12 f6c3cfeb in ?? () in plugins/crashdetect.so
23/07/2021 18:38:49 [debug] Registers:
23/07/2021 18:38:49 [debug] EAX: 00000000 EBX: 00000000 ECX: 00000006 EDX: fffd89cd
23/07/2021 18:38:49 [debug] ESI: 00000002 EDI: 00000038 EBP: fffd89bc ESP: fffd8900
23/07/2021 18:38:49 [debug] EIP: f67b429e EFLAGS: 00010293
23/07/2021 18:38:49 [debug] Stack:
23/07/2021 18:38:49 [debug] ESP+00000000: 00000009 098c83a0 fffd8978 00000800
23/07/2021 18:38:49 [debug] ESP+00000020: 00000009 00000002 f67b4189 f688f000
23/07/2021 18:38:49 [debug] ESP+00000040: fffd89bc 00000000 00000002 00000001
23/07/2021 18:38:49 [debug] ESP+00000060: 00d30000 00020001 0100072a 00000001
23/07/2021 18:38:49 [debug] ESP+00000080: f688f000 00000002 fffd8ae8 f67b8d2f
23/07/2021 18:38:49 [debug] ESP+000000a0: fffd89bc 00000000 00000003 00000000
23/07/2021 18:38:49 [debug] ESP+000000c0: 00000800 00000000 fffd89cd 0002d301
23/07/2021 18:38:49 [debug] ESP+000000e0: 00011a00 43dc0000 43b68000 00000000
23/07/2021 18:38:49 [debug] ESP+00000100: 001effff 7277656e 6e69626f 4d202d20
23/07/2021 18:38:49 [debug] ESP+00000120: ffff7e6e 00000000 00000008 ffffffff
23/07/2021 18:38:49 [debug] ESP+00000140: 352e3839 00000030 00000000 00000000
23/07/2021 18:38:49 [debug] ESP+00000160: 098be350 f7c25000 00000000 f7b80326
23/07/2021 18:38:49 [debug] ESP+00000180: 00000000 00000000 00800000 fffd8ac0
23/07/2021 18:38:49 [debug] ESP+000001a0: 09e49b30 fffd8ac0 fffd8b08 080e4dd6
23/07/2021 18:38:49 [debug] ESP+000001c0: 7277656e 6e69626f 4d202d20 00000b7f
23/07/2021 18:38:49 [debug] ESP+000001e0: 00000f68 09b8ea40 fffd8b38 f67b8ebb
23/07/2021 18:38:49 [debug] ESP+00000200: f67b8e57 f3ff9010 00000f68 080950e4
23/07/2021 18:38:49 [debug] ESP+00000220: 000d5e18 00000000 f67b8e50 f6c67000
23/07/2021 18:38:49 [debug] ESP+00000240: 09b8ea40 00000117 fffd8cdc f5b3963c
23/07/2021 18:38:49 [debug] ESP+00000260: ffffffec 098b25c0 00000000 fffd8b94
23/07/2021 18:38:49 [debug] ESP+00000280: 09b8ea40 00000000 01a4e2b0 000d5e18
23/07/2021 18:38:49 [debug] ESP+000002a0: 000d5db8 00000035 fffd8be4 098ba568
23/07/2021 18:38:49 [debug] ESP+000002c0: f66b9d8c fffd8c1c 0000cd75 f7f27000
23/07/2021 18:38:49 [debug] ESP+000002e0: 5b000000 0005abfa 567023b0 0006617e
23/07/2021 18:38:49 [debug] ESP+00000300: f6c67000 09bc4200 f3ff9010 f6c368e1
23/07/2021 18:38:49 [debug] ESP+00000320: 00000000 fffd8c7c 09dd8ac0 cdb50e00
23/07/2021 18:38:49 [debug] ESP+00000340: 00000000 f7f8d040 f7f8d544 fffd8cb4
23/07/2021 18:38:49 [debug] ESP+00000360: f6c67890 f3ff9010 01a4e298 f6c3cfeb
23/07/2021 18:38:49 [debug] ESP+00000380: f6c3cf87 f40d3e34 09b8ea40 f6c41e89
23/07/2021 18:38:49 [debug] ESP+000003a0: 01a4a460 01a4e2b0 f3ffe020 01a4e2a0
23/07/2021 18:38:49 [debug] ESP+000003c0: 000ed384 000d5e18 f40d7158 f6c36f55
23/07/2021 18:38:49 [debug] ESP+000003e0: 00000000 00000058 3cf34eb6 f6c67000
23/07/2021 18:38:49 [debug] Loaded modules:
23/07/2021 18:38:49 [debug] 00000000 - 00187f43 samp03svr
23/07/2021 18:38:49 [debug] f7f60000 - f7f60d2c linux-gate.so.1
23/07/2021 18:38:49 [debug] f7f4e000 - f7f50eec /lib32/libdl.so.2
23/07/2021 18:38:49 [debug] f7f2b000 - f7f4b463 /lib32/libpthread.so.0
23/07/2021 18:38:49 [debug] f7d4c000 - f7f36f2a /lib32/libstdc++.so.6
23/07/2021 18:38:49 [debug] f7c48000 - f7d4b6ec /lib32/libm.so.6
23/07/2021 18:38:49 [debug] f7c29000 - f7c459cc /lib32/libgcc_s.so.1
23/07/2021 18:38:49 [debug] f7a3e000 - f7c2f0b3 /lib32/libc.so.6
23/07/2021 18:38:49 [debug] f7f61000 - f7f8bf9b /lib/ld-linux.so.2
23/07/2021 18:38:49 [debug] f7698000 - f7a40ac7 plugins/mysql_static.so
23/07/2021 18:38:49 [debug] f768d000 - f76953b3 /lib32/librt.so.1
23/07/2021 18:38:49 [debug] f6c79000 - f6c8b268 /lib32/libnss_files.so.2
23/07/2021 18:38:49 [debug] f6c68000 - f6c779b4 plugins/sscanf.so
23/07/2021 18:38:49 [debug] f7f57000 - f7f5a310 plugins/CTime.so
23/07/2021 18:38:49 [debug] f6761000 - f6908168 plugins/SKY.so
23/07/2021 18:38:49 [debug] f6c1f000 - f6c673d4 plugins/crashdetect.so
23/07/2021 18:38:49 [debug] f668e000 - f6762b05 plugins/streamer.so
23/07/2021 18:38:49 [debug] f6559000 - f66927d8 plugins/pawnraknet.so

**Comment by NexiusTailer** [comment]
Try to test with and without [this](https://github.com/oscar-broman/samp-weapon-config/commit/4012a02ce149d414d64047064957b8ef4948dd6f) single change. I hope the problem is in something else, but anyway this can be quickly reverted if your doubt is confirmed. At the moment, it hasn't been tested enough on a large player base, unfortunately.

**Comment by elvianod982** [comment]
I reverted just that single change and the server hasn't crashed. Before, it would crash within 15 minutes of starting up. We're at 10 hours of uptime now, so it was certainly that commit it seems.

**Comment by NexiusTailer** [comment]
@ADRFranklin do you see any noticeable problems on the plugin side that can be fixed there, or will you have to undo [commit 4012a02](https://github.com/oscar-broman/samp-weapon-config/commit/4012a02ce149d414d64047064957b8ef4948dd6f)?

**Comment by elvianod982** [comment]
Any movement on this case? I would say at the very least https://github.com/oscar-broman/samp-weapon-config/commit/4012a02ce149d414d64047064957b8ef4948dd6f needs reverting for now until time can be devoted to investigate in more detail, as in its current state this include is pretty much unusable unless one disables that fix.
