### ISSUE TITLE
SetCustomFallDamage Parachute Bug

### ISSUE THREAD

**Issue by codectile** [oscar-broman/samp-weapon-config#21]
The player loses his health almost 90 per cent on respawn after dying using his parachute, when `SetCustomFallDamage` is set to `false`. All other things works fine when it is set to true. This same situation is applicable for this (https://github.com/oscar-broman/samp-weapon-config/issues/17) bug too.
![sa-mp-032](https://cloud.githubusercontent.com/assets/8154609/6326048/a3b79d74-bb73-11e4-8fcc-6580aa91e2d7.png)
![sa-mp-033](https://cloud.githubusercontent.com/assets/8154609/6326049/a6cbdc0a-bb73-11e4-99a5-f0c2c1dfab69.png)
![sa-mp-034](https://cloud.githubusercontent.com/assets/8154609/6326050/a6d121ce-bb73-11e4-90f5-91bd1ba895bb.png)

**Comment by oscar-broman** [comment]
Could you get debug output from when that happens?

**Comment by codectile** [comment]
Yes I do get the output.
![sa-mp-035](https://cloud.githubusercontent.com/assets/8154609/6328055/090b881a-bb89-11e4-897f-f7935b79373c.png)

**Comment by oscar-broman** [comment]
I mean the debug output from when you lose 90.

**Comment by codectile** [comment]
No, there is no debug message printed at that time.

**Comment by Crayder** [comment]
If you have the debug enabled it has to print something :/

**Comment by codectile** [comment]
The debug message in the above picture is the only message which gets printed after the spawn(with 90% damage).
