### ISSUE TITLE
Server Crash Problem - Paying scripters.

### ISSUE THREAD

**Issue by AlfieBW** [oscar-broman/samp-weapon-config#210]
Hello guys,
Recently I have been trying to install this system and it's working well as a dmg system but my server keeps crashing when I shoot someone on the body while he sits as a passenger in a motorbike.

Crash detect shows that it comes from _SKY.so_ plugin and _UpdateHealthBar_ function And _UpdateSyncData_ function.

If none doesn't know anything about this problem I will be happy to pay someone to remove all features from this system and keep only the damage system, nothing else.

I really like to use this system in my server, it works fine and is simple to edit the values of each weapon.

**Comment by ADRFranklin** [comment]
Could you create a new gamemode with the most basic reproduceable example of this issue happening and provide me it? 

This is so I can test with the exact same resources and config as you.

**Comment by AlfieBW** [comment]
Okay, until I get those sources for you, is it possible to get an edition of this include which has only the damage system on it and nothing of other features like animations. text draws. pause kill. vehicle kill.

Can you provide me your discord so we can share those sources. I even have hosted a server just to test this problem.

**Comment by ADRFranklin** [comment]
You can contact me on discord with JustMichael#7884
