### ISSUE TITLE
Hide Health bar

### ISSUE THREAD

**Issue by kolor4do** [oscar-broman/samp-weapon-config#216]
Is it possible to disable the life textdraw? It is not correctly adjusted for those who use a mod

**Comment by NexiusTailer** [comment]
Relared to #187?

**Comment by kolor4do** [comment]
Yes... I wanted to use the original life, without textdraw. 
`EnableHealthBarForPlayer ` worked, but life was no longer updated

**Comment by NexiusTailer** [comment]
As it's not possible to hide it without switching to native (client) hp and death logic.
