### ISSUE TITLE
Driver does call OnPlayerGiveDamage

### ISSUE THREAD

**Issue by Zbyss** [oscar-broman/samp-weapon-config#229]
https://github.com/oscar-broman/samp-weapon-config/blob/34037120c1869519cf6542c4597cf2c4772efcf9/weapon-config.inc#L3244-L3247

This statement breaks the drive-by damage.

Current state: https://streamable.com/2v245z
After commenting out: https://streamable.com/ybh1z2

**Comment by ADRFranklin** [comment]
Alright thanks, do you want to maybe make a PR for this change?

**Comment by Zbyss** [comment]
Done. https://github.com/oscar-broman/samp-weapon-config/pull/230
