### ISSUE TITLE
Can We Turn Of on-screen TextDraw indicators of damage given/taken?

### ISSUE THREAD

**Issue by Fariz0077** [oscar-broman/samp-weapon-config#231]
The Textdraw Indicator Is Making So Many Issues In RP Servers 
If There Is Any Way To Turn It Off Please Let Me Know

**Comment by Fariz0077** [comment]
![1](https://user-images.githubusercontent.com/75154237/145223825-498abfbb-0053-4b67-94d1-b518954fd37d.PNG)
![2](https://user-images.githubusercontent.com/75154237/145223829-ef5a6054-a193-4b78-bdac-ae7787b77c22.PNG)
I Mean Is There Any Way To Turn Off This Damage Indication?

**Comment by ADRFranklin** [comment]
Did you bother looking at the documentation ? There is a function to disable it and it's called `SetDamageFeed`.

**Comment by Fariz0077** [comment]
Thanks A Lot And Where Can I Find The Documentation?

**Comment by ADRFranklin** [comment]
In the main repo, literally scroll down.
