### ISSUE TITLE
Probably wrong variable in damage feed (needs to be tested)

### ISSUE THREAD

**Issue by NexiusTailer** [oscar-broman/samp-weapon-config#250]
Recently I noticed that `s_DamageFeedHitsGiven` is used to get the issuerid's health inside damage feed taken message:

https://github.com/oscar-broman/samp-weapon-config/blob/7d41f6945d3bd5d9997f554f7a954ea79766aae0/weapon-config.inc#L5601

Seems like it was confused with `s_DamageFeedHitsTaken` array which is used everywhere else inside this condition except this single place:
![image](https://user-images.githubusercontent.com/13169094/195635067-c6257f72-669d-40c4-9174-138334a467ec.png)

I need someone who have time now to test it and confirm that when you got some damage from the other player, your damage feed tells you wrong health amount in (brackets). If this is really a mistake, I'll change this to `s_DamageFeedHitsTaken` if it's needed.

**Comment by ADRFranklin** [comment]
I have been using this for sometime on my server now, and everything seems fine for me.

**Comment by ADRFranklin** [comment]
nvm, it was just a small spectate issue, the health is of the offending player

**Comment by ADRFranklin** [comment]
@NexiusTailer I'll try that code out and see what happens tomorrow.

**Comment by NexiusTailer** [comment]
So, does it need to be changed finally? I assume it is, but just to be sure it really shows relevant player's health after changing `s_DamageFeedHitsGiven` to `s_DamageFeedHitsTaken`.

**Comment by ADRFranklin** [comment]
I think both will work, but in both places you used the playerid even for HitsGiven, which is where I expect you got the wrong information. Instead would it have not made sense to use the attacking playerid for `s_DamageFeedHitsGiven`?

**Comment by NexiusTailer** [comment]
So, yeah, I used `playerid` in HasGiven because this is how it's done now here:
https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5601

If both will work (using issuerid for HasGive variable or playerid for HasTake), then good, but I think it was just a typo mistake initially, somewhere in [those PRs](https://github.com/oscar-broman/samp-weapon-config/pull/118).

**Comment by NexiusTailer** [comment]
I should've tested it first before any assumptions as looks like this is my mistake though. Tested it with and without the `Given` -> `Taken` correction I made sure the current version works correctly with both given and taken damage names displayed, while replacing `s_DamageFeedHitsGiven` with `Taken` variable name [here](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L5621), messages about the taken damage stopped coming at all :/

Can be closed then, sorry for false find.
