### ISSUE TITLE
 I have a problem with HIT_INVALID_DAMAGE 

### ISSUE THREAD

**Issue by LeonardoClark** [oscar-broman/samp-weapon-config#257]
Some APK's are not counting the damage, that's right declined, for this reason HIT_INVALID_DAMAGE, has anyone else had this problem? what did you do to solve it?

If I disable this part, will it be possible to use damage hack?

What I noticed is that the damage sent from the APK is different from what is in the include. However I tried to adjust manually, it solved for some.

```
if ((err = ProcessDamage(playerid, issuerid, amount, weaponid, bodypart, bullets))) {
   if (err == WC_INVALID_DAMAGE) {
	 AddRejectedHit(issuerid, playerid, HIT_INVALID_DAMAGE, weaponid, _:amount);
  }

 if (err != WC_INVALID_DISTANCE) {
	 OnInvalidWeaponDamage(issuerid, playerid, amount, weaponid, bodypart, err, false);
 }

 return 0;
}
```

**Comment by NexiusTailer** [comment]
Find all the contacts of each android client author and tell them to fix it from their side. There is nothing to fix from the server damage system, it works normally.
