### ISSUE TITLE
how to put callback Onplayergivedamage and onplayertakedamage

### ISSUE THREAD

**Issue by KirovNoName** [oscar-broman/samp-weapon-config#262]
how to enable the callback like Onplayertakedamage and onplayergivedamage without removing #incluce <weaponconfig>

**Comment by mysy00** [comment]
Use OnPlayerDamage instead.
You most likely don't want to access real natives since weapon-config will be responsible for handling it.

**Comment by KirovYuri** [comment]
> Use OnPlayerDamage instead. You most likely don't want to access real natives since weapon-config will be responsible for handling it.

what if i put undefined onplayerdamage it will enable it?

**Comment by NexiusTailer** [comment]
> > Use OnPlayerDamage instead. You most likely don't want to access real natives since weapon-config will be responsible for handling it.
> 
> what if i put undefined onplayerdamage it will enable it?

It's already declared in weapon-config, so it won't be undefined when you add this public into your gamemode.
