### ISSUE TITLE
Health and armor recovery when damaging

### ISSUE THREAD

**Issue by PazzOnee** [oscar-broman/samp-weapon-config#271]
https://streamable.com/ah7gul

On link you can see video where i shooting player with weapon, and a little percent of health, armor is giving back to player

**Comment by NexiusTailer** [comment]
Do you have any other scripts included? Try to test it on a bare gamemode to see if this is still occuring or not.

**Comment by PazzOnee** [comment]
@NexiusTailer I tested it right now with samp server, and when i upgraded R3 Samp server to open.mp, problem is going, i tested it with samp server r3 + pawnraknet and SKY, no problem, next testing with open.mp + raknet = problem, i will open issue on open.mp
