### ISSUE TITLE
Textdraw clearing issue

### ISSUE THREAD

**Issue by v0UwUK6CmCrjVB1PAtRb** [oscar-broman/samp-weapon-config#298]
I've noticed that on occasions, the damage textdraw does not clear.

Most commonly it happens when taking damage and dying very shortly after, leaving the damage TD stuck on the screen, even when you respawn.

There's other occasions where it happens as well, but I do not have more information on the circumstances that lead up to it.

Any thoughts?

**Comment by NexiusTailer** [comment]
Can you test it and maybe try to reproduce on a blank gamemode without any places where the other textdraws could be created as well? Just to be sure that it's exactly an issue of weapon-config and not something else outside it in your scripts.
