### ISSUE TITLE
Preventing the spawn after the Death Animation finishes.

### ISSUE THREAD

**Issue by JasonAndrews** [oscar-broman/samp-weapon-config#30]
I think it would be awesome to have the option to completely prevent the spawning of players when their death animation finishes (from OnPlayerPrepareDeath).

I'd love to be able to simply apply the death animation for as long as the 'respawn_time' parameter specifies with -1 being forever.

So basically, being able to prevent OnPlayerDeath.

Example One:
If a player falls to his death from the sky, I'd like to be able to play the animation as usual but instead of the player playing the animation and then despawning, I could let him lay on the ground.

This would be great as well (same thing as above but when the deaths occur inside vehicles):
Example:
If a group of people are in a vehicle and it explodes due to collision/weapon damage, then I could allow them to all play the death animation and then make them all lay where the car exploded in the animation without having to use SetPlayerPos after OnPlayerDeath and OnPlayerSpawn.

Also see: http://forum.sa-mp.com/showpost.php?p=3405048&postcount=91.

It always feels like I explain these sort of things horribly, let me know if I did and I'll try clear it up more :D

**Comment by Crayder** [comment]
Well explained. I like the whole idea. The vehicle explosion thing is in development already, but the laying on ground is a good idea. Say a vehicle explodes, I think all the players should end up on the ground in positions according to their seat position (this could be useful http://pastebin.com/rKDAhRkv). 

OnPlayerDeath is already prevented, the vehicle explosion and a few other things are the only things standing Slice's way.

'Hooking' all spawn handlers would be necessary but it would be very badass. This would require hooking SetSpawnInfo, SpawnPlayer, OnPlayerRequestSpawn (not as important, but for the current class selection problems it is pretty important to play along with), and most importantly OnPlayerSpawn. Maybe other things could also be played with like custom SetPlayerTeam, SetPlayerSkin, SetPlayerSpawnWeapon (new func), and some others that could go along with this whole custom spawn thing.

Out of all of this, I really like the '-1' infinite death freeze duration. This could be very useful.

Lastly, it seems Slice has been busy lately (as he said somewhere) so I'm not pushing any ideas his way too quick, but this could be a stable milestone addition.

**Comment by JasonAndrews** [comment]
Yeah, that would be awesome as well, ending up on the ground according to the seat they were in. I don't think OnPlayerDeath is fully prevented though. Slice mentioned in his documentation it is avoided in most situations, but not all of them. When i was testing the include, i think the ones that are not avoided are the ones I want to avoid the most.

**Comment by oscar-broman** [comment]
8dd217eabe148a0dfd9264259987ee2c46c6dac6

**Comment by oscar-broman** [comment]
65509fb681ea1d835680508a15eefe7e4ded803d should cover any other deaths you wish to prevent.

For your script, the API will appear the same as any other death:
1. `OnPlayerDamage`
2. `OnPlayerDamageDone`
3. `OnPlayerPrepareDeath`
4. `OnPlayerDeath`
5. `OnPlayerDeathFinished`

However, internally, returning 0 in `OnPlayerDamage` or modifying `amount` so the player will not die causes the player to get respawned in place and carry on like nothing happened.

**Comment by JasonAndrews** [comment]
Awesome Slice!

Thanks a lot, will get to testing this as soon as I get a few minutes free.

**Comment by JasonAndrews** [comment]
Slice, does the 65509fb version compile for you? 

I just updated the include with the code from the 65509fb version and I get a large amount of errors when trying to compile my GM with the updated include.

**Comment by oscar-broman** [comment]
What errors? Could be `AddPlayerClass`. I'll look into it.

**Comment by oscar-broman** [comment]
Oh, I saw what it was. 4299403563d114ebd4facadea14ac97e97992b50 works properly.

**Comment by JasonAndrews** [comment]
Awesome, that update fixed most of the errors though there is still two left.

..\pawno\include\weapon-config.inc(4234) : warning 202: number of arguments does not match definition
..\pawno\include\weapon-config.inc(5063) : error 025: function heading differs from prototype

**Comment by oscar-broman** [comment]
Do you use `OnPlayerDeathFinished`? It looks like this now:
```
forward OnPlayerDeathFinished(playerid, bool:cancelable);
```

**Comment by JasonAndrews** [comment]
Whoops, thanks, forgot to update that.

Going to test it now.

**Comment by JasonAndrews** [comment]
Got some testing done earlier.

It all works really well! The change to OnPlayerDeathFinished is awesome :D It seems like it works really well and properly from what I've tested.

I've only noticed one bug though (not sure if it's a bug but it seems like it is). Sometimes when you die inside a vehicle (tested several times and I think it depends on the vehicle - from what I remember, it bugs out with a Cheetah but not with SAN News Helicopter and Bullet), you get respawn when you finish your animation, it respawns you on the spot (instantly respawns like you mentioned above) which is awesome but you get bugged out. Your skin is set to the CJ skin every now and then. It didn't happen each time though.

I'll be testing some more in the morning and will hopefully be able to explain it better :D

**Comment by oscar-broman** [comment]
Respawning when dying in some vehicles is somethingI'm trying to fix.

Do you use this include in your gamemode? Do you use player classes or `SetSpawnInfo`? Do you spawn the player in `OnPlayerReqiestClass` or return 1?

**Comment by JasonAndrews** [comment]
Ok awesome :D

I use SetSpawnInfo (only in my SpawnCharacter function at the moment).

I return 0 in OnPlayerRequestClass.

I'll be testing a bit more today.

**Comment by JasonAndrews** [comment]
Hi Slice,

I've detailed a few tests that I carried out with different callbacks returning 0 or 1 too see if it works properly.

I'm not sure which way it's suppose to be so I thought I'd detail the results for you so you can easily see what happened.

Here are the results - http://pastebin.com/Yvdxywkr

**Comment by oscar-broman** [comment]
Did you press F4 in those tests?

**Comment by JasonAndrews** [comment]
No, not once.

**Comment by oscar-broman** [comment]
Why do you always return 0 in `OnPlayerRequestClass`?

I suppose the issue is when the player never gets a class, and each "true death" (yes, True Blood fans, I named it after that) sends the player back to class selection.

Do you use `SpawnPlayer` in `OnPlayerConnect`? The script you put on pastebin shouldn't spawn players, unless `OnPlayerRequestClass` returns 1 in another place (i.e. you ran a filterscript and return 1 in a gamemode).

`OnPlayerRequestClass` is actually a bit problematic when it comes to filterscripts/gamemodes.

**Comment by JasonAndrews** [comment]
I return 0 in OnPlayerRequestClass because I want to have full control over how and when the player spawns. It's a roleplay script so I completely avoid classes and automatically spawn them when they log in or successfully create a new character. I only call SpawnPlayer once in my script, it's in a function called SpawnCharacter(playerid). Both logging in and creating a new character calls the function when ready.

I know the script won't spawn players because it's only those particular callbacks i felt mattered when posting the test results.

Should I be returning 1 (or 0) in some of these callbacks for it to work with weapon-config.inc?

**Comment by oscar-broman** [comment]
I think the best solution is to add a way to completely disable class selection. I'll add something like `ToggleClassSelection(toggle)`.

I will also try to replicate the default behavior, however.

**Comment by JasonAndrews** [comment]
That would be amazing :D

**Comment by oscar-broman** [comment]
This seems to be impossible to achieve without a few seconds of craziness. When a player dies (a real `OnPlayerDeath`), some internal timer in the game is created for the player to respawn.
No matter what I tried, the player will always spawn again after 2-3 seconds.

Also ran into some strange behavior..

http://www.youtube.com/watch?v=kaliz9_tfBk

**Comment by JasonAndrews** [comment]
Ah, I was afraid of that being the case. Thanks for trying though :D

The include is still amazing and I know in my case, it will cut off countless hours when creating a death script.

I think that also happened to me a few weeks but I couldn't get it to happen again so I wasn't sure if it actually happened or not XD

**Comment by Crayder** [comment]
:O 
I want to drive the blown up car! I used to do that all the time on the PSP GTA's (of course that required a few cheats to be done rapidly).

On topic, this sucks. At least you've come this close though.

**Comment by oscar-broman** [comment]
Actually, I got it working pretty nicely. For some vehicles, the player will need to be frozen for a short duration (2-3 seconds) after the explosion, but the camera can still be moved. For some vehicles, the player can start moving instantly.

I'll do some more testing before pushing the code.

**Comment by JasonAndrews** [comment]
Awesome :D 

I can do some testing when the code is pushed as well.

**Comment by Crayder** [comment]
One thing I really hate is parachute deaths. My custom map is 200 meters off of ground level so no matter how far I'm falling the parachute is equipped and the gliding animation is applied, this causes death when I fall more than like 5 meters if I have a parachute. Is there any way around this?

**Comment by oscar-broman** [comment]
If you return 0 or reduce amount when someone takes falling damage, they will get automatically respawned if they die from a parachute.
