### ISSUE TITLE
warning 219: local variable "hour" shadows a variable at a preceding level

### ISSUE THREAD

**Issue by v0UwUK6CmCrjVB1PAtRb** [oscar-broman/samp-weapon-config#301]
The following warnings are logged after updating to the default openmp includes with qawno:

```
weapon-config.inc(6532) : warning 219: local variable "hour" shadows a variable at a preceding level
weapon-config.inc(6532) : warning 219: local variable "minute" shadows a variable at a preceding level
weapon-config.inc(6532) : warning 219: local variable "second" shadows a variable at a preceding level
```

I'm aware I can hide them with `//#pragma warning disable 219` and they're only warnings (not errors) but figured it wouldn't harm to report it.

**Comment by NexiusTailer** [comment]
You probably have `hour`, `minute` and `second` names declared in your gamemode as global variables.
Change their names to more unique in your script in this case.
