### ISSUE TITLE
AddPlayerClass

### ISSUE THREAD

**Issue by testik123123** [oscar-broman/samp-weapon-config#318]
Не работает с плагином по снятию лимита на скины, а именно:
при добавленном weapon config при скине id выше 319 после OnPlayerDeath багается GetPlayerState, ставится 7 и всё. Без конфига бага нет, после смерти спавнится нормально

**Comment by NexiusTailer** [comment]
Поддержки расширения лимитов здесь по умолчанию не предусмотрено и такое придётся редактировать в файле руками. Но конечно, если мы говорим про классы, а не про скины, потому что сами скины здесь никак и нигде не трогаются.

Как минимум, вот [здесь [1]](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L1056), [здесь [2]](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L1836) и вот [здесь [3]](https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L1858) (заменить значение 320 на твои текущие лимиты).

**Comment by NexiusTailer** [comment]
Внёс некоторые доработки в сам weapon-config.

Теперь можно перед его подключением объявить дефайн `WC_MAX_CLASSES`, где 320 (стандартное значение) можно поменять на любое другое, какое требуется, если лимиты на классы были также повышены вместе с лимитами на скины.
