### ISSUE TITLE
Deaths in vehicles, bugged.

### ISSUE THREAD

**Issue by zeelorenc** [oscar-broman/samp-weapon-config#32]
Plain and simple. Did some testing:

Ended up teleporting to default class spawn with a cigar.

1. Slain myself in a vehicle (set my own health to -1).
2. Someone killed me in my car.
3. Someone killed me in my car, in an interior.

**Comment by oscar-broman** [comment]
It seems sending the player into spectate mode when inside a vehicle cause problems.
