### ISSUE TITLE
OnPlayerDeath >> OnPlayerDeathFinished

### ISSUE THREAD

**Issue by testik123123** [oscar-broman/samp-weapon-config#321]
Снова здравствуйте. Такой момент заметил, что OnPlayerDeathFinished не срабатывает только в одном случае: если убить игрока (проигрывается анимация смерти), но продолжать при этом в него стрелять (он умирает якобы ещё раз), соответственно после смерти либо не вызывается OnPlayerSpawn, либо ставит виртуальный мир и интерьер 0. Если пустить 3 пули, дав игроку умереть спокойно, то OnPlayerDeathFinished срабатывает нормально и OnPlayerSpawn тоже. Не знаете в чем может быть дело?

**Comment by testik123123** [comment]
> Снова здравствуйте. Такой момент заметил, что OnPlayerDeathFinished не срабатывает только в одном случае: если убить игрока (проигрывается анимация смерти), но продолжать при этом в него стрелять (он умирает якобы ещё раз), соответственно после смерти либо не вызывается OnPlayerSpawn, либо ставит виртуальный мир и интерьер 0. Если пустить 3 пули, дав игроку умереть спокойно, то OnPlayerDeathFinished срабатывает нормально и OnPlayerSpawn тоже. Не знаете в чем может быть дело?

----------------------------------
Понял в чем дело: я менял значение SetPlayerHealth(playerid, 8000000.0 + float(health)) на SetPlayerHealth(playerid, 0.1 + float(health)), отключал HealthBar чтобы работал стандартный SAMP худ. Теперь другой вопрос: как сделать, чтобы было значение 8000000.0 и при этом работал стандартный худ SAMP?

**Comment by testik123123** [comment]
> > Снова здравствуйте. Такой момент заметил, что OnPlayerDeathFinished не срабатывает только в одном случае: если убить игрока (проигрывается анимация смерти), но продолжать при этом в него стрелять (он умирает якобы ещё раз), соответственно после смерти либо не вызывается OnPlayerSpawn, либо ставит виртуальный мир и интерьер 0. Если пустить 3 пули, дав игроку умереть спокойно, то OnPlayerDeathFinished срабатывает нормально и OnPlayerSpawn тоже. Не знаете в чем может быть дело?
> 
> Понял в чем дело: я менял значение SetPlayerHealth(playerid, 8000000.0 + float(health)) на SetPlayerHealth(playerid, 0.1 + float(health)), отключал HealthBar чтобы работал стандартный SAMP худ. Теперь другой вопрос: как сделать, чтобы было значение 8000000.0 и при этом работал стандартный худ SAMP?

Может какую проверку можно сделать по типу "если игрок уже умер, то наносить урон ему сверху нельзя?" и тогда работал бы стандартный худ HP.

**Comment by NexiusTailer** [comment]
> Понял в чем дело: я менял значение SetPlayerHealth(playerid, 8000000.0 + float(health)) на SetPlayerHealth(playerid, 0.1 + float(health)), отключал HealthBar чтобы работал стандартный SAMP худ. Теперь другой вопрос: как сделать, чтобы было значение 8000000.0 и при этом работал стандартный худ SAMP?

Никак. А иначе бы и не было такого костыля в дамаг системе изначально, если бы без него можно было бы обойтись.

> Может какую проверку можно сделать по типу "если игрок уже умер, то наносить урон ему сверху нельзя?" и тогда работал бы стандартный худ HP.

В оригинальном wc такой проблемы нет, это проблема твоих доработок (в них и делай все подобные проверки, но вряд ли они помогут)
