### ISSUE TITLE
Trying to bypass the Death Animation.

### ISSUE THREAD

**Issue by JasonAndrews** [oscar-broman/samp-weapon-config#34]
Yo.

I've finally got my GM to the point where I am getting to work on the death system.

I have it all working (well the parts I want to work) but there's an issue with the death animation that I was hoping you could help me fix. (Skip to *TO THE POINT for a step-by-step explanation).

Under OnPlayerDamage, I switch between the players death state (ALIVE, WOUNDED or DEAD).
If the person is alive, i allow the damage to be done. If the damage >= (health+armour), then I set the persons death state to WOUNDED. At this stage, the death animation is played (as they 'die' according to the weapon-config include) but I freeze them in that animation.

When they're WOUNDED and they take x damage (30 for example), then they are set to the DEAD state.

*TO THE POINT
The issue I am having is that the animation (when they are already in the animation) gets played every time they are shot.
This is how it goes right now:
OnPlayerDamage(..) -> ALIVE -> Damage the player.
OnPlayerDamage(..) -> ALIVE -> Damage the player - Animation Plays (is now WOUNDED).
OnPlayerDamage(..) -> WOUNDED -> Return 0 -> Animation Plays (is now DEAD).
OnPlayerDamage(..) -> DEAD -> Return 0 -> Animation Plays (is still DEAD).

This is how I want it to go:
OnPlayerDamage(..) -> ALIVE -> Damage the player.
OnPlayerDamage(..) -> ALIVE -> Damage the player - Animation Plays (is now WOUNDED).
OnPlayerDamage(..) -> WOUNDED -> Return 0 -> Animation does not play (already playing) and is now DEAD.
OnPlayerDamage(..) -> DEAD -> Return 0 -> Animation does not play (already playing) and is still DEAD.

I tried fixing it on my end but everything I tried failed. I thought returning 0 in OnPlayerDamage would fix it (by never entering OnPlayerDamageDone) but it didn't.

Would be great to have a configuration setting like AllowDeathAnimationToReplay(bool:value) that would not re-apply the death animation if the death animation is already playing.

(Not sure if this makes sense so please let me know if that's the case :D)

Thanks.

**Comment by oscar-broman** [comment]
I think you need to set the health to 1 or something when they die the first time.

**Comment by JasonAndrews** [comment]
Okay thanks. I tried it but it didn't fix it from what I tried.

This is the code I am using under OnPlayerDamage. I was hoping that if the player is WOUNDED/DEAD, then returning 0 will stop them bullet from registering which would internally stop the animation from playing.

switch(AccountInfo[playerid][pPlayerDeathState]) { //Switch between the players death state (ALIVE, WOUNDED or DEAD).
	
		case PLAYER_DEATH_STATE_ALIVE: { //The player is ALIVE.
			if(amount >= (hp + armour)) { //If the player was ALIVE be should now be WOUNDED.				
				AccountInfo[playerid][pPlayerDeathState] = PLAYER_DEATH_STATE_WOUNDED;				
				RefreshDeathLabel(playerid);
			}				
		}
		case PLAYER_DEATH_STATE_WOUNDED: { //The player is already WOUNDED.			
			p_damageTakenWhileWounded[playerid] += amount;
			
			if(p_bleedOutTime[playerid] == -1) p_bleedOutTime[playerid] = PLAYER_WOUNDED_BLEED_OUT;
			
			if(p_damageTakenWhileWounded[playerid] > 30)  { //The player was WOUNDED but is now DEAD.				
				//The player has taken too much damage while WOUNDED, now 'kill' them.
				BleedoutPlayer(playerid); //Sets the players death state to DEAD.
			}
			return 0;
		}
		case PLAYER_DEATH_STATE_DEAD: { //The player is already DEAD.
			return 0;
		}	
	}

Does this look like it should do that? And where would you recommend setting the players health to 1 or should I do that in another callback?

Thanks.

**Comment by Y-Less** [comment]
I don't think you understand what "TL;DR" means...

**Comment by JasonAndrews** [comment]
I was going to put it as something different like "TO THE POINT" but when I was originally writing it, I didn't expect the part after the "TL:DR" to be so big :P

**Comment by Y-Less** [comment]
That's fine, it just amused me that the summary was longer than the original explanation.

**Comment by codectile** [comment]
@oscar-broman Is the development paused or terminated ?

**Comment by oscar-broman** [comment]
I've been very busy lately. I'll wrap this project up when I get the time.

**Comment by Crayder** [comment]
This is kinda regarding this and the vehicle ankm bypass problem... i suggest putting dead players in spectate mode, and creating an actor in their death position.

**Comment by oscar-broman** [comment]
Why would you put an actor if you want to prevent the death? That's the problem here. Dying in an exploding vehicle looks just fine, but problems arise when the death is to be prevented.

**Comment by Crayder** [comment]
I was talking about the death, like instead of actually having the players look at their body create an actor. This would prevent the ability for them to get out of the death anim by entering a near vehicle.

**Comment by Yiin-** [comment]
You can try to create an invisible RC vehicle in different interior at actor position and spectate it... I guess it should do the job ^_^
