### ISSUE TITLE
OnPlayerDeath is not called if player explodes inside a vehicle. 

### ISSUE THREAD

**Issue by Yiin** [oscar-broman/samp-weapon-config#35]
Steps to reproduce:
1. Get into vehicle.
2. Put it on fire
3. Wait for explosion
4. ??
5. Play gets spawned twice before https://github.com/oscar-broman/samp-weapon-config/commit/ee4831c48c5ae3e46305150d039a81d4a89f37e8, and his death is simply skipped in current version. OnPlayerSpawn is called once tho.

**Comment by Yiin-** [comment]
It looks like it is intended. Option to force kill player if he dies in exploaded vehicle would be awesome.

**Comment by oscar-broman** [comment]
I'm confused. What's wrong exactly?

**Comment by Yiin-** [comment]
If player is in vehicle, and vehicle explodes, player just respawns. I'd wanted to him to die. Achieved that by modifying code in OnPlayerDeath callback.

Changes starts at ~90 line.
https://www.diffchecker.com/efx1u01i

**Comment by oscar-broman** [comment]
Uhh, are you sure you're not returning 0 in `OnPlayerDamage, `OnPlayerDeath` or `OnPlayerDeathFinished`?
