### ISSUE TITLE
Cannot read from file: "weapon-config"

### ISSUE THREAD

**Issue by banksSAMP** [oscar-broman/samp-weapon-config#39]
Hey.

Whenever I compile my "fresh" gamemode I get this.

\gamemodes\bare.pwn(4) : fatal error 100: cannot read from file: "weapon-config"
Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase
1 Error.

You recommended me that I update my include files, which ones do I need to update specificly?

Edit: If someone thats reading this has a working setup, I would greatly appreciate if they could upload/send me the includes for 0.3.7 or something! :p

Banks

**Comment by Crayder** [comment]
Obviously you're a complete newb at this. You must put the include in your includes folder.

i.e. Take the include file you downloaded from here, navigate to your pawno folder, paste the include into the includes folder there.

**Comment by banksSAMP** [comment]
It's in there, though...
http://i.imgur.com/rnxagsI.png

**Comment by Crayder** [comment]
Then you aren't using the right pawno. Open the pawno.exe directly from that pawno folder and open the file manually.

**Comment by banksSAMP** [comment]
That fixed it, thanks!
