### ISSUE TITLE
While you are in vehicle and falling and try to get out the player receives damage

### ISSUE THREAD

**Issue by Jessyy** [oscar-broman/samp-weapon-config#4]
I noticed while you are in a vehicle (tested only on nrg) and falling and you will try to get out the player will receive damage.

Video: https://www.youtube.com/watch?v=Ub0uJlVBkt0
Info: A friend of mine recorded me while he was spectating me, this way the camera is so close to vehicle (the spec system is a little fk)

Info to reproduce: While falling the vehicle pitch must be something like this https://dl.dropboxusercontent.com/u/51829909/dfdfdf.png (i love paint :smile:)
The amount of damage you will receive is related to velocity (the higher it is the damage will be even greater)

**Comment by oscar-broman** [comment]
The video clip is private.

This should be easy to fix, nevertheless. I'll look into it.

**Comment by Jessyy** [comment]
lol... totally forgot about the to set the video to be public... try now
