### ISSUE TITLE
Increase player damage

### ISSUE THREAD

**Issue by PatchwerkQWER** [oscar-broman/samp-weapon-config#40]
Hi,

I think this sounds nice. Something like `SetPlayerWeaponDamage` or `IncreaseWeaponDamage`
What you think?  I should look on it when I wil have time.

Cheers

**Comment by oscar-broman** [comment]
It could already be done in `OnPlayerDamage`, but a more official way would be nice too. I'm just afraid it might get a bit messy.

What is it you're really trying to do? Set the damage for each player, or each player matching a certain criteria?

I think it's overkill to make per-player damage.

Example:
```
public OnPlayerDamage(...)
{
    if (issuerid != INVALID_PLAYER_ID && g_PlayerGang[issuerid] == SOME_GANG) {
        amount *= 1.5;
    }

    return 1;
}
```

I think it's better to get used to writing damage logic in `OnPlayerDamage` than adding verbose damage adjustment.

**Comment by PatchwerkQWER** [comment]
Oh yes, `OnPlayerDamage` sounds like it's better way to increase player damage.

I close this issue. Thanks
