### ISSUE TITLE
OnVehicleSpawn Is Not Called

### ISSUE THREAD

**Issue by Lawrence-Stockton** [oscar-broman/samp-weapon-config#44]
If weapon-config is included in your game-mode, the callback OnVehicleSpawn will not be called.

**Comment by oscar-broman** [comment]
Are the vehicles created by a filterscript?

**Comment by Lawrence-Stockton** [comment]
At one point, they were and I assumed this was the problem. I then moved the vehicles to my game-mode, and the issue still occurred. I'm using AddStaticVehicleEx, though I've tried using CreateVehicle and AddStaticVehicle (all inside of my game-mode). When SetVehicleToRespawn is used, OnVehicleSpawn won't be called if the weapon-config include was compiled with the game-mode.

**Comment by oscar-broman** [comment]
@nickdodd25 must have messed something up in #41

**Comment by mannyone** [comment]
I am having this issue too but I never had it happen until recently.

**Comment by nickdodd25** [comment]
I can confirm this issue. I will add a pull request within the next hour with a fix for it. The issue was from the way i was calling OnVehicleSpawn. I also fixed a issue where vehicles could possibly call OnVehicleDeath and OnVehicleSpawn multiple times.

**Comment by Jeroen52** [comment]
I am also starting to experience problems with SetVehicleToRespawn since
one of the latest revisions of weapon-config.
When vehicles respawn they are not refueled and any attached objects are
not removed. Admin spawned vehicles are normally set to despawn on
respawning, and are now going back to the spawn point.
Op 21 dec. 2015 02:30 schreef "Nick" <notifications@github.com>:

**Comment by nickdodd25** [comment]
@Jeroen52 @Lawrence-Stockton @mannyone Can you three test my fork with the fixes for this. https://github.com/nickdodd25/samp-weapon-config 

I don't want to make a pull request until i know it works. OnVehicleSpawn seems to be getting called correctly now on my server.

**Comment by Lawrence-Stockton** [comment]
Something I've come across when compiling is a warning from adding the siren parameter to AddStaticVehicleEx. Aside from that, everything seems fine from what I've tested and OnVehicleSpawn is being called correctly now.

**Comment by nickdodd25** [comment]
Ok i added the siren param. 

And that's great that its working correctly now.

**Comment by Lawrence-Stockton** [comment]
Yeah, I'll notify if anything pertaining to vehicles isn't functioning correctly, though everything seems to be working fine at the moment and working as it should.

Thank you for the help!

**Comment by Jeroen52** [comment]
The bugfix works for me, I'm opening a merge request.
