### ISSUE TITLE
Player killed on <= 0.0 damage

### ISSUE THREAD

**Issue by Jeroen52** [oscar-broman/samp-weapon-config#51]
This may be somewhat of a non-issue, but I'm posting it here anyways for discussion purposes.

https://github.com/oscar-broman/samp-weapon-config/blob/3acad301fe85bed5479111fe49d7b6191b696eab/weapon-config.inc#L4640..L4642

https://github.com/oscar-broman/samp-weapon-config/blob/3acad301fe85bed5479111fe49d7b6191b696eab/weapon-config.inc#L4646..L4648

Whenever you inflict 0.0 or less damage to someone, the player dies.

I am fairly certain that this is not a bug, but those who are inexperienced with the weapon-config code might think that this is a bug or that the include is bugged.

_I'm even going to use this to make an easy instakill weapon._

**Comment by oscar-broman** [comment]
This is on purpose. Amount 0 means *all the damage*. If you wish to do no damage at all, simply return false.

**Comment by Jeroen52** [comment]
I already thought that it was the case.
But maybe those unfamiliar might think that the code is fucked. What if it is stated somewhere in the readme that you need to ``return 0;`` to do no damage and that ``amount = 0.0`` kills.

**Comment by oscar-broman** [comment]
https://github.com/oscar-broman/samp-weapon-config#new-callbacks

**Comment by Jeroen52** [comment]
@oscar-broman Why did I not read that?
 I must be blind.
