### ISSUE TITLE
Death Skipping sometimes hangs

### ISSUE THREAD

**Issue by nickdodd25** [oscar-broman/samp-weapon-config#62]
I seemed to have found a weird issue where i return 0 under OnPlayerDamage, basically a god mode, and i blow up in a vehicle and weapon config respawns you/skips death like its suppose to. 

But sometimes it hangs. The user will stay frozen. And sometimes the user gets put into class selection. The class selection one seems less common than the frozen user one.

This is the debug output.

[15:25:06] Vehicle id: 904 died from playerid: 0
[15:25:07] (wc) OnPlayerDeath(0 died by 255 from 65535)
[15:25:07] [death] nickd25 died 255
[15:25:07] (wc:0) OnPlayerTakeDamage(0 took 3.300000 from 65535 by 54 on bodypart 3)
[15:25:07] (wc:0) Requested class: 309
[15:25:07] (wc:0) Skipping death - class selection skipped
[15:25:07] (wc:0) Death skipped

And that's it. I can however trigger this debug code, which is death skipping being finished.

[15:25:11] (wc:0) Death skip end

I can trigger this by playing an animation from my animation browser, or simply spawning a vehicle.

I have not tested this on a blank mode/server yet, only have on my server. But the only time this seems to happen is when a user blows up in a vehicle when god mode is enabled/returning 0 under onplayerdamage

EDIT: This happened when returning 1 like normal.

I have had the issue again with the user going to class selection. I even got the debug lines.

[Wed Jan 04 05:23:53 PM] (wc) OnPlayerDeath(0 died by 255 from 65535)
[Wed Jan 04 05:23:53 PM] (wc) OnPlayerDamageDone(65535 did 99.000000 to 0 with 51 on bodypart 0)
[Wed Jan 04 05:23:53 PM] [Death] Playerid 0 killed by 65535 reason 51
[Wed Jan 04 05:23:53 PM] 14[DEATH]02[0] 07nickd25 died.
[Wed Jan 04 05:23:53 PM] [death] nickd25 died 255
[Wed Jan 04 05:23:53 PM] Vehicle died id: 969
[Wed Jan 04 05:23:56 PM] (wc:0) Requested class: 310
[Wed Jan 04 05:23:56 PM] (wc:0) True death class selection

**Comment by nickdodd25** [comment]
@oscar-broman I was just curious if you ever looked into this? It has almost been a month since i opened this issue.

**Comment by nickdodd25** [comment]
I seemed to have fixed the class selection issue. I ended up making adding a function to weapon-config that checks if the user is getting resynced.

`IsUserGettingResynced(playerid)
{
	return s_BeingResynced[playerid];
}
`

Then i just added 
`if(IsUserGettingResynced(playerid)) return 1;`
to onplayerrequestclass and onplayerspawn

Seems to have partially fixed this issue. But i do still get the issue where the user freezes after a resync.

I have tried changing around include orders to see if it was just a issue with the order of the hooks. But that did not seem to change anything.

**Comment by oscar-broman** [comment]
When you say freeze, what do you mean? The same type of freeze that happens when the skin is changed during an animation or TogglePlayerControllable type freeze?

**Comment by nickdodd25** [comment]
It is a frozen user as if TogglePlayerControllable is not being disabled. 
It seems as if this line https://github.com/oscar-broman/samp-weapon-config/blob/master/weapon-config.inc#L2877 is not being triggered correctly.

If you like i can show you exactly how to replicate the bug on my local server. Let me know and i can send you the ip if you would like to do that.

**Comment by oscar-broman** [comment]
Ok write me on Gitter and we'll arrange something.

**Comment by nickdodd25** [comment]
Did you get my message on gitter?

**Comment by nickdodd25** [comment]
Ok to replicate this issue, simply install weapon config and the sky plugin on a fresh grandlarc install. And only return 0 under onplayerdamage. For me it seems that the user is always frozen until they do another animation, or they try to enter a vehicle that is close by. 

`[10:08:11] Requested class: 1`
`[10:08:11] OnPlayerDamage(0, 0.000000, 65535, 51, 0)`
`[10:08:11] (wc:0) Requested class: 1`
`[10:08:11] (wc:0) Skipping death - class selection skipped`
`[10:08:11] (wc:0) Death skipped`
A few moments later i was close enough to enter a vehicle, and this triggered the death skip end when i pressed enter.
`[10:08:32] (wc:0) Death skip end`
