### ISSUE TITLE
stock IsPlayerSpawned crash, changed to Public works

### ISSUE THREAD

**Issue by rt-2** [oscar-broman/samp-weapon-config#64]
I got "runtime error 11: devided by zero" in OnPlayerWeaponShot, unless I change the IsPlayerSpawned stock function into a forwarded public function.

Now everything works fine,, weird.
Thought I'd let you guys know...

Thank you,
rt-2

**Comment by oscar-broman** [comment]
Remove your IsPlayerSpawned - weapon-config will make its own.

**Comment by rt-2** [comment]
I am talking about the 'IsPlayerSpawned' inside weapon-config that I need to modify.

**Comment by oscar-broman** [comment]
Then it is most definitely a compiler bug - do you have those error messages in your log? I need to see where it is triggered.

**Comment by rt-2** [comment]
It's triggered from `OnPlayerGiveDamage` in 
```c
if (!IsPlayerSpawned(playerid)) {
	// Make sure the rejected hit wasn't added in OnPlayerWeaponShot
	if (!IsBulletWeapon(weaponid) || s_LastShot[playerid][e_Valid]) {
		AddRejectedHit(playerid, damagedid, HIT_NOT_SPAWNED, weaponid);
	}
	return 0;
}
```
`AddRejectedHit` is not called and the error is returned if `IsPlayerSpawned` is a stock

**Comment by oscar-broman** [comment]
I think another include or perhaps your gamemode declares a IsPlayerSpawned. It could be that it is declared as static, which should not cause problems but I have encountered problems with the Pawn compiler before where a static function sharing the name of a global function caused strange behavior.

Could you search through your project for IsPlayerSpawned?

**Comment by rt-2** [comment]
It's a native in YSF.

**Comment by rt-2** [comment]
I didn't mean to 'close' this issue, I pressed the wrong button

**Comment by oscar-broman** [comment]
The one in YSF will not be correct and should not be used. I'd suggest doing something like this:
```
#define IsPlayerSpawned IsPlayerSpawned_YSF
#include <YSF>
#undef IsPlayerSpawned
#include <weapon-config>
```

**Comment by rt-2** [comment]
So the one in weapon-config willl be compatible with YSF AND weapon-config?
I just don't wanna break my YSF either.

Thank you,

**Comment by oscar-broman** [comment]
Yes it will be. The one in YSF is very simple - it just checks the player state and whether spawn info has been given. weapon-config does that also.

https://github.com/kurta999/YSF/blob/94baaf7b946ddf0a34820b2d4ac734774ecb116f/src/Natives.cpp#L2141
