### ISSUE TITLE
weapon-config crash

### ISSUE THREAD

**Issue by ghost** [oscar-broman/samp-weapon-config#65]
[debug]  Accessing element at index 65535 past array upper bound 999
[debug] AMX backtrace:
[07:56:02] [debug] #0 000342b0 in AddRejectedHit (playerid=65535, damagedid=2, reason=19, weapon=49, i1=1111883777, i2=0, i3=0) at C:\pawno\include\weapon-config.inc:5308
[debug] #1 00024624 in public OnPlayerTakeDamage (playerid=2, issuerid=65535, Float:amount=49.50000, weaponid=49, bodypart=3) at C:\pawno\include\weapon-config.inc:3373
[debug]

**Comment by rt-2** [comment]
Seems like your MAX_PLAYER is 1000?
You probably have something in one of your `OnPlayerTakeDamage` that tries to use 65535 in a player function or array.
rt-2
