### ISSUE TITLE
SetPlayerHealth Issue

### ISSUE THREAD

**Issue by ant298** [oscar-broman/samp-weapon-config#66]
Good evening, 

I just set up this include and SKY plugin; Everything is working except one thing: a god cmd i had on my gamemode. This command uses to set the player health to a big amount and a timer refull the health if it decreased 

```
CMD:god(playerid, params[])
{
    if(PlayerInfo[playerid][Level] < 7) return SendClientMessage(playerid, red, "You are not allowed to use this command");
    if(PlayerInfo[playerid][God] == 0)
	{
        PlayerInfo[playerid][God] = 1;
   	    SetPlayerHealth(playerid,100000);
		GivePlayerWeapon(playerid,16,50000); GivePlayerWeapon(playerid,26,50000);
        SendClientMessage(playerid,green,"GodMode ON.");
    }
	else
	{
	    PlayerInfo[playerid][God] = 0;
	    SendClientMessage(playerid,red,"GodMode OFF.");
        SetPlayerHealth(playerid, 100);
	}
	return 1;
}

function GodUpdate()
{
	foreach(new i : Player) if(PlayerInfo[i][God] == 1) SetPlayerHealth(i,100000), RepairVehicle(GetPlayerVehicleID(i)), SetVehicleHealth(GetPlayerVehicleID(i),1000000.0);
	return 1;
}
```

From now, when I try this: It is like if I did nothing, not increasing the health, like if i have 100 HP

Have you any ideas about what could be the problem

Thanks

**Comment by oscar-broman** [comment]
You can just do this:
```
public OnPlayerDamage(...)
{
    if (PlayerInfo[playerid][God]) {
        return 0;
    }

    return 1;
}
```

**Comment by ant298** [comment]
Thanks!

**Comment by Y-Less** [comment]
Total aside: why not create a `God` iterator?  Doing this almost defeats the point of foreach:

```pawn
foreach(new i : Player) if(PlayerInfo[i][God] == 1) SetPlayerHealth(i,100000), RepairVehicle(GetPlayerVehicleID(i)), SetVehicleHealth(GetPlayerVehicleID(i),1000000.0);
```

Instead, just use:

```pawn
foreach(new i : God) SetPlayerHealth(i,100000), RepairVehicle(GetPlayerVehicleID(i)), SetVehicleHealth(GetPlayerVehicleID(i),1000000.0);
```

**Comment by ant298** [comment]
Thanks for this remark however do you think it would useful just for 2-3 person MAX ? 
 
  Le Lun. j mars PM à 16:04, Y-Less<notifications@github.com> a écrit :   
Total aside: why not create a God iterator? Doing this almost defeats the point of foreach:
foreach(new i : Player) if(PlayerInfo[i][God] == 1) SetPlayerHealth(i,100000), RepairVehicle(GetPlayerVehicleID(i)), SetVehicleHealth(GetPlayerVehicleID(i),1000000.0);
Instead, just use:
foreach(new i : God) SetPlayerHealth(i,100000), RepairVehicle(GetPlayerVehicleID(i)), SetVehicleHealth(GetPlayerVehicleID(i),1000000.0);

**Comment by Y-Less** [comment]
It is designed for sparse arrays - the less people you have, the better it is to use `foreach`.

**Comment by ant298** [comment]
Alright, i will start using it more for slots i had with PlayerInfo! Thanks for the info

**Comment by ant298** [comment]
Alright, i will start using it more for slots i had with PlayerInfo! Thanks for the info. When you are talking of the "Worst way", what are you think that could be better ?

**Comment by rt-2** [comment]
Iterators, like he said, doesn't need all the memory between data,
compared to an array who 'needs' to know that every unused slot is 'empty' and will keep that data and you will loop through all instead of just the one you need, like with Iterators.

**Comment by Jeroen52** [comment]
You could also do something like this, might look a bit cleaner.

```pawn
public OnPlayerDamage(...)
{
	if (PlayerInfo[playerid][God])
		return 0;

	return 1;
}
```

**Comment by Crayder** [comment]
@Jeroen52 That's literally the exact same thing that Slice posted above, without two brackets. That was pointless to suggest...

**Comment by Jeroen52** [comment]
@Crayder I know that it is the exact same thing that Slice posted, I am just suggesting a different style of programming.
