### ISSUE TITLE
Bullet Hit Types

### ISSUE THREAD

**Issue by f0Re3t** [oscar-broman/samp-weapon-config#73]
https://github.com/oscar-broman/samp-weapon-config/blob/9359ccd7682d9b0b7d64b2e874d8a9febd8e57e5/weapon-config.inc#L3428

http://wiki.sa-mp.com/wiki/BulletHitTypes

**Comment by rt-2** [comment]
Yeah its to avoid someone trying to crash other player with invalid vallues I think.

**Comment by f0Re3t** [comment]
why five if the maximum of four ?

**Comment by oscar-broman** [comment]
5 is used when you shoot an NPC, I think. Could someone double-check?

**Comment by NexiusTailer** [comment]
@oscar-broman  It seems that it isn't, NPC detects as regular players, i.e. hittype 1
![sa-mp-000](https://user-images.githubusercontent.com/13169094/29586130-59c2104e-8792-11e7-938d-e41697db4fb7.png)
