### ISSUE TITLE
Vehicles cannot be damaged by weapons

### ISSUE THREAD

**Issue by Matz47** [oscar-broman/samp-weapon-config#74]
No matter what I do, the vehicles which have drivers inside of them do not receive any fired bullet damage. Any idea?

Edit: corrected sentence

**Comment by rt-2** [comment]
use
```
		SetVehiclePassengerDamage(true);
		SetVehicleUnoccupiedDamage(true);
```
in `OnGameModeInit`

**Comment by Matz47** [comment]
I have them already
