### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by yPower** [oscar-broman/samp-weapon-config#76]
Error In Console

[debug] Run time error 19: "File or function is not found"
[debug]  FreezeSyncData
[debug]  SetFakeFacingAngle
[debug]  SendLastSyncData
[debug]  ClearAnimationsForPlayer
[debug]  SetKnifeSync
[debug]  SetFakeHealth
[debug]  SetFakeArmour
[debug]  PlayerTextDrawSetPosition
[debug]  SpawnPlayerForWorld
[debug]  SetDisableSyncBugs
[debug] Run time error 19: "File or function is not found"
[debug]  FreezeSyncData
[debug]  SetFakeFacingAngle
[debug]  SendLastSyncData
[debug]  ClearAnimationsForPlayer
[debug]  SetKnifeSync
[debug]  SetFakeHealth
[debug]  SetFakeArmour
[debug]  PlayerTextDrawSetPosition
[debug]  SpawnPlayerForWorld
[debug]  SetDisableSyncBugs
Script[gamemodes/MGM.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0

**Comment by Renato-Garcia** [comment]
You need SKY plugin: https://github.com/oscar-broman/SKY

**Comment by yPower** [comment]
Thanks Renato-Garcia, I Don't Know that have It Plugin Lol, in Releases
