### ISSUE TITLE
onplayertakedamage crashes server

### ISSUE THREAD

**Issue by aminadjk** [oscar-broman/samp-weapon-config#79]
[20/02/2018 16:43:03] britishonlysilence killed Arab_PLayer with Vehicle
[20/02/2018 16:43:03] [debug] Server crashed while executing script.amx
[20/02/2018 16:43:03] [debug] AMX backtrace:
[20/02/2018 16:43:03] [debug] #0 0000002e in ?? () at <unknown file>:0
[20/02/2018 16:43:03] [debug] #1 0000002e in public OnPlayerTakeDamage () at <unknown file>:0

It always crashes with this reason, and always when someone kills someone with VEHICLE.

I'm using YOUR include and its probably your code problem? i have onplayerdeath == invalid playerid and != invalid, everything under these codes, same for onplayerdamage callback.

**Comment by oscar-broman** [comment]
My guess is that you do something like this:
```SourcePawn
weapon_name[weapon]
```

**Comment by aminadjk** [comment]
Where? OnplayerDeath, or onPlayerdamage?

I didn't modify your onplayertakedamage.

**Comment by oscar-broman** [comment]
Could be either of them. You are not using a debugger so I can't know for sure.

Could you show your code for OnPlayerDamage and OnPlayerDeath?

**Comment by aminadjk** [comment]
new gunname[32];
          GetWeaponName(reason, gunname, sizeof(gunname));
          printf("%s killed %s with %s",PlayerName(killerid),PlayerName(playerid),gunname);

I can't really show onplayerdeath it's consisting of private things. Can you tell how I can enable debug, it will show the error line,  right?

**Comment by oscar-broman** [comment]
Just show any code that uses `reason` or `weapon`

**Comment by aminadjk** [comment]
if(killerid != INVALID_PLAYER_ID)
        {
          new death_reason[ 34 ], string[ MAX_PLAYER_NAME + 5 ]; //this?
          switch ( reason )
		  {

                    // case 0... etc messages
But it happens only when someone kills someone with VEHICLE, So i don't think this is an issue.

**Comment by oscar-broman** [comment]
VEHICLE is 255, which is a much higher value than the others.
Use a debugger.

First do this: https://github.com/Zeex/samp-plugin-crashdetect/wiki/Compiling-scripts-with-debug-info

Then install this: https://github.com/Zeex/samp-plugin-crashdetect/releases/tag/v4.18.1

**Comment by aminadjk** [comment]
Well im already using crashdetect -d3 -r, and its unknown file, always as in my first msg.

**Comment by oscar-broman** [comment]
Then you are doing something wrong.

**Comment by aminadjk** [comment]
I don't think so because it doesn't crash without weaponconig.

**Comment by aminadjk** [comment]
Your onplayertakedamage has 255 as issuer/playerid which is invalid and I fixed it long ago for myself (addrejectedhit) thing, could you check it again?

however i replaced the include and im lazy to find out which one line of addrejectedhit from onplayertakedamage it was

**Comment by oscar-broman** [comment]
It's in your code. Go debug.

**Comment by Jeroen52** [comment]
@aminadjk I'm sure he meant with "you are doing something wrong" as in you're not using Crashdetect properly. If you're using Crashdetect properly it should give you a stacktrace that helps you resolve the issue, and if it is actually an error in weapon-config it should make that clear.
