### ISSUE TITLE
OPD, amount (I think it's something to do with amount) bug.

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#8]
When using the following code, I sometimes die from falling short distances. Some other times I survive the very long falls.

```
public OnPlayerDamage(&playerid, &Float:amount, &issuerid, &weapon, &bodypart)
{
    if (weapon == WEAPON_COLLISION && amount < 7.5) // Ignore low fall damage
        return 0;
    return 1;
}
```

**Comment by oscar-broman** [comment]
Could be a 0.3.7 bug. If you always return 0 in `OnPlayerDamage`, can you die from a 1000ft fall?
