### ISSUE TITLE
why this include is fucked up?

### ISSUE THREAD

**Issue by aminadjk** [oscar-broman/samp-weapon-config#80]
im serious, why enablevehiclefriendlyfire();

doesnt make any vehicles damageable? eventhough I USE setplayerteam everywhere...

what is this crap?

how can i enablevehiclefriendlyfire then?

**Comment by oscar-broman** [comment]
This is not a place to vent your frustration.

If I recall correctly, this is a limitation in weapon-config and you should not use EnableVehicleFriendlyFire.

Feel free to modify the include and send a pull request.
