### ISSUE TITLE
Should you call DamagePlayer at OnPlayerDamage?

### ISSUE THREAD

**Issue by AmirSavand** [oscar-broman/samp-weapon-config#87]
Will it result in an infinite loop?

**Comment by BigETI** [comment]
DamagePlayer calls InflictDamage https://github.com/oscar-broman/samp-weapon-config/blob/0cc1598b486c12790eac9d6200a91c0345cfcc5b/weapon-config.inc#L1281 where InflictDamage calls https://github.com/oscar-broman/samp-weapon-config/blob/0cc1598b486c12790eac9d6200a91c0345cfcc5b/weapon-config.inc#L4608

That means the answer to your question is under certain circumstances "yes".

**Comment by AmirSavand** [comment]
So I should do some kinda check before calling `DamagePlayer`.

Thanks @BigETI
