### ISSUE TITLE
Rocket Launcher and Heatseeker (others untested)

### ISSUE THREAD

**Issue by Crayder** [oscar-broman/samp-weapon-config#9]
When hitting somebody with a missile, they can take a missile straight to the face and only lose ~5 to 7 health. Didn't realize until some random guy came in my server and hit me it the face with a missile.

**Comment by oscar-broman** [comment]
Did you change anything in `OnPlayerDamage`? Either way, I'll test this.

**Comment by Crayder** [comment]
do you wanna just come in my server so i can show the things to you ?

**Comment by oscar-broman** [comment]
What's the IP and when are you usually online?

**Comment by Crayder** [comment]
I'm home now. I'll be online:

HostName: Test Server [0.3.7]
Address:  68.45.78.40:7777
Password: Crayder

**Comment by oscar-broman** [comment]
Can't reproduce. Closing for now.
