### ISSUE TITLE
Hiding health bar

### ISSUE THREAD

**Issue by MarkTimber** [oscar-broman/samp-weapon-config#92]
Is there any way of hiding created health bar? I understand, that include works the way, that health is infinite for everyone, but then someone comes to my server with hud modifications, it looks like this: [image](https://media.discordapp.net/attachments/553920292980916238/555113484367429655/sa-mp-046.png?width=831&height=468). Waiting for answer!

**Comment by juanpenia** [comment]
as far as I know, you can't hide the game health bar

**Comment by MarkTimber** [comment]
I was inneed of hiding health bar created by include, because it was created with textdraws and textdraws with graphical modifications looks like I showed in an image. Anyway, I disabled all the functions SetFakeHealth and SetFakeArmour (just by commenting them.), but the problem still remained. After few hours, I figured out, that include OxygenControler has the same function, so custom health bar were created two times.

**Comment by Crayder** [comment]
The alternative would be just not disabling it. It's a feature of your server, if player's don't like a server because it doesn't coincide with their mods then that should be for them to deal with. Simple as dat imo. The same applies if it is you using the mod, you're butchering the functionality of this include and screwing with every player's game play because you want to use a mod in that case.

**Comment by MarkTimber** [comment]
Weapon-config has enabled infinite health for every player as soon as they connect/spawn, for unique after death ability to move camera around. I disabled only textdraws which indicates health and armour, so now player has infinite health and everyone can see that not changing health and armour bar. I realised, that this could be even usefull, then player can not track his health, armour, stamina. Player should attract his attention on some in-game things, like blood, or some animations on low health. This could be way more interesting to play, they would not be able to inform coleges from police department for example, how much health do they have, there would be no such rush on shootings, etc, etc.

**Comment by MarkTimber** [comment]
Btw, I live in lithuania, server will for lithuanian players too. Most of them use mods, and simply without ability to use them, they would better just find another server and play there, despite the fact, that in main systems would be alot alot better.

**Comment by Crayder** [comment]
In that case, I absolutely support what you're doing! Great explanation as well.

If I get the time soon I'll personally reconstruct my previous colored health bars edit, and include ability to disable the textdraw per player. It's a little tough with my schedule (three jobs is a bit more work than I thought xD), but I may even be able to do this at work this weekend (weekend are slow at USI).

Ps. Reading my previous comment again I realize I may have sounded like a dick, I was just explaining my opinion/thought process and I apologize if you took offense lol

**Comment by MarkTimber** [comment]
It's alright, no inneed to apologize, I took no offense. Thanks for comment and support!
