### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Money1010** [oscar-broman/samp-weapon-config#94]
When I try the following:
`public OnPlayerDamage(24,DAMAGE_TYPE_STATIC,40);`

I get these errors:

`C:\Users\gamin\OneDrive\Desktop\Gamemode\pawno\include\weapon-config.inc(5448) : error 004: function "WC_OnPlayerDamage" is not implemented
C:\Users\gamin\OneDrive\Desktop\Gamemode\pawno\include\weapon-config.inc(5715) : error 025: function heading differs from prototype`

**Comment by Money1010** [comment]
All I'm tryina do is learn how to set the damage on weapons and what ids do the limbs have, if you added some sort of template on the functions it would be a lot easier for people like me who are completely new to coding.

**Comment by Y-Less** [comment]
That's not valid code.  It looks like you are confusing calling a function and defining a function.  Or you are trying to pattern match, but pawn doesn't support that.
