### ISSUE TITLE
A cleanup of the project

### ISSUE THREAD

**Issue by ADRFranklin** [oscar-broman/samp-weapon-config#95]
I think it's about time, this include was cleaned up a little, to prevent the many issues that people are facing using it. 

This isn't a huge job as the code isn't at all bad. But it has it's drawbacks in some use cases.

**Comment by zile42O** [comment]
Yo Franklin i have question for you, about const in string parameters, the last compilers will warn with warning to we need have for example
public function(string[]) 
So must be const string[] 
I saw you do that, but you removed that, so i need answer what about that?

**Comment by Y-Less** [comment]
They aren't generally `const` in callbacks (publics), just elsewhere.  Functions you call, not functions called from the VM.

**Comment by zile42O** [comment]
ApplyAnimation
OnPlayerPrepareDeath
i get warnings on that but i fixed that for me

**Comment by ADRFranklin** [comment]
If you think you have time to do it, then make a PR. I am a little busy with SKY right now.

**Comment by zile42O** [comment]
Sure, i will do that later
